# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Landmark.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Landmark(object):
    def setupUi(self, Landmark):
        Landmark.setObjectName("Landmark")
        Landmark.resize(787, 539)
        self.centralwidget = QtWidgets.QWidget(Landmark)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Display_Landmarks = matplotlibWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Landmarks.sizePolicy().hasHeightForWidth())
        self.Display_Landmarks.setSizePolicy(sizePolicy)
        self.Display_Landmarks.setObjectName("Display_Landmarks")
        self.gridLayout_2.addWidget(self.Display_Landmarks, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_LoadLandmark = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_LoadLandmark.setObjectName("Button_LoadLandmark")
        self.gridLayout.addWidget(self.Button_LoadLandmark, 0, 0, 1, 1)
        self.Text_Filename = QtWidgets.QTextBrowser(self.groupBox_2)
        self.Text_Filename.setObjectName("Text_Filename")
        self.gridLayout.addWidget(self.Text_Filename, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_autodetect = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_autodetect.setMinimumSize(QtCore.QSize(215, 0))
        self.groupBox_autodetect.setObjectName("groupBox_autodetect")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_autodetect)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_autodetect)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.d_SourceDetector = QtWidgets.QDoubleSpinBox(self.groupBox_autodetect)
        self.d_SourceDetector.setDecimals(1)
        self.d_SourceDetector.setMaximum(400.0)
        self.d_SourceDetector.setObjectName("d_SourceDetector")
        self.gridLayout_4.addWidget(self.d_SourceDetector, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_autodetect)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_autodetect)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.d_ObjectDetector = QtWidgets.QDoubleSpinBox(self.groupBox_autodetect)
        self.d_ObjectDetector.setDecimals(1)
        self.d_ObjectDetector.setMaximum(400.0)
        self.d_ObjectDetector.setObjectName("d_ObjectDetector")
        self.gridLayout_4.addWidget(self.d_ObjectDetector, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_autodetect)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.LabelPixSpace = QtWidgets.QLabel(self.groupBox_autodetect)
        self.LabelPixSpace.setObjectName("LabelPixSpace")
        self.gridLayout_4.addWidget(self.LabelPixSpace, 2, 0, 1, 3)
        self.Button_accptPxSpace = QtWidgets.QPushButton(self.groupBox_autodetect)
        self.Button_accptPxSpace.setObjectName("Button_accptPxSpace")
        self.gridLayout_4.addWidget(self.Button_accptPxSpace, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_autodetect)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Button_defineROI = QtWidgets.QPushButton(self.groupBox)
        self.Button_defineROI.setEnabled(True)
        self.Button_defineROI.setCheckable(True)
        self.Button_defineROI.setChecked(False)
        self.Button_defineROI.setFlat(False)
        self.Button_defineROI.setObjectName("Button_defineROI")
        self.gridLayout_3.addWidget(self.Button_defineROI, 0, 0, 1, 2)
        self.Button_lockEarpin = QtWidgets.QPushButton(self.groupBox)
        self.Button_lockEarpin.setEnabled(True)
        self.Button_lockEarpin.setObjectName("Button_lockEarpin")
        self.gridLayout_3.addWidget(self.Button_lockEarpin, 0, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.TxtEarpinX = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.TxtEarpinX.setDecimals(1)
        self.TxtEarpinX.setMaximum(10000.0)
        self.TxtEarpinX.setSingleStep(0.1)
        self.TxtEarpinX.setObjectName("TxtEarpinX")
        self.gridLayout_3.addWidget(self.TxtEarpinX, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 2, 1, 1)
        self.TxtEarpinY = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.TxtEarpinY.setDecimals(1)
        self.TxtEarpinY.setMaximum(10000.0)
        self.TxtEarpinY.setSingleStep(0.1)
        self.TxtEarpinY.setObjectName("TxtEarpinY")
        self.gridLayout_3.addWidget(self.TxtEarpinY, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.Button_Done = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Done.setObjectName("Button_Done")
        self.verticalLayout.addWidget(self.Button_Done)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        Landmark.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Landmark)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 26))
        self.menubar.setObjectName("menubar")
        Landmark.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Landmark)
        self.statusbar.setObjectName("statusbar")
        Landmark.setStatusBar(self.statusbar)

        self.retranslateUi(Landmark)
        QtCore.QMetaObject.connectSlotsByName(Landmark)

    def retranslateUi(self, Landmark):
        _translate = QtCore.QCoreApplication.translate
        Landmark.setWindowTitle(_translate("Landmark", "Landmark Definition"))
        self.groupBox_2.setTitle(_translate("Landmark", "GroupBox"))
        self.Button_LoadLandmark.setText(_translate("Landmark", "Load Landmark Image"))
        self.groupBox_autodetect.setTitle(_translate("Landmark", "Pixel Spacing"))
        self.label_4.setText(_translate("Landmark", "<html><head/><body><p>Source-Detector: d<span style=\" vertical-align:sub;\">SD </span>=</p></body></html>"))
        self.label_6.setText(_translate("Landmark", "cm"))
        self.label_5.setText(_translate("Landmark", "<html><head/><body><p>Object-Detector: d<span style=\" vertical-align:sub;\">OD</span> =</p></body></html>"))
        self.label_7.setText(_translate("Landmark", "cm"))
        self.LabelPixSpace.setText(_translate("Landmark", "Pixel Spacing:"))
        self.Button_accptPxSpace.setText(_translate("Landmark", "Lock"))
        self.groupBox.setTitle(_translate("Landmark", "Earpin"))
        self.Button_defineROI.setText(_translate("Landmark", "Define ROI"))
        self.Button_lockEarpin.setText(_translate("Landmark", "Lock"))
        self.label_9.setText(_translate("Landmark", "x="))
        self.label_10.setText(_translate("Landmark", "y="))
        self.Button_Done.setText(_translate("Landmark", "Done"))

from matplotlibwidgetFile import matplotlibWidget
