# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Landmark.ui'
#
# Created: Wed Feb 14 15:57:58 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Landmark(object):
    def setupUi(self, Landmark):
        Landmark.setObjectName(_fromUtf8("Landmark"))
        Landmark.resize(1089, 610)
        self.centralwidget = QtGui.QWidget(Landmark)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Display_xsum = matplotlibWidget(self.centralwidget)
        self.Display_xsum.setGeometry(QtCore.QRect(80, 459, 400, 90))
        self.Display_xsum.setObjectName(_fromUtf8("Display_xsum"))
        self.Display_ysum = matplotlibWidget(self.centralwidget)
        self.Display_ysum.setGeometry(QtCore.QRect(490, 49, 90, 400))
        self.Display_ysum.setObjectName(_fromUtf8("Display_ysum"))
        self.Display_Landmarks_2 = matplotlibWidget(self.Display_ysum)
        self.Display_Landmarks_2.setGeometry(QtCore.QRect(-420, 0, 400, 400))
        self.Display_Landmarks_2.setObjectName(_fromUtf8("Display_Landmarks_2"))
        self.Display_Landmarks = matplotlibWidget(self.centralwidget)
        self.Display_Landmarks.setGeometry(QtCore.QRect(80, 49, 400, 400))
        self.Display_Landmarks.setObjectName(_fromUtf8("Display_Landmarks"))
        self.groupBox_autodetect = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_autodetect.setGeometry(QtCore.QRect(590, 30, 171, 161))
        self.groupBox_autodetect.setObjectName(_fromUtf8("groupBox_autodetect"))
        self.Button_accptPxSpace = QtGui.QPushButton(self.groupBox_autodetect)
        self.Button_accptPxSpace.setGeometry(QtCore.QRect(10, 120, 151, 31))
        self.Button_accptPxSpace.setObjectName(_fromUtf8("Button_accptPxSpace"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_autodetect)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 158, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Button_defineROI = QtGui.QPushButton(self.layoutWidget)
        self.Button_defineROI.setEnabled(True)
        self.Button_defineROI.setObjectName(_fromUtf8("Button_defineROI"))
        self.gridLayout_4.addWidget(self.Button_defineROI, 0, 0, 1, 1)
        self.Button_defineMan = QtGui.QPushButton(self.layoutWidget)
        self.Button_defineMan.setObjectName(_fromUtf8("Button_defineMan"))
        self.gridLayout_4.addWidget(self.Button_defineMan, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_autodetect)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 151, 67))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.bed_top = QtGui.QLineEdit(self.layoutWidget1)
        self.bed_top.setObjectName(_fromUtf8("bed_top"))
        self.gridLayout_5.addWidget(self.bed_top, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.bed_bot = QtGui.QLineEdit(self.layoutWidget1)
        self.bed_bot.setObjectName(_fromUtf8("bed_bot"))
        self.gridLayout_5.addWidget(self.bed_bot, 1, 1, 1, 1)
        self.LabelPixSpace = QtGui.QLabel(self.layoutWidget1)
        self.LabelPixSpace.setObjectName(_fromUtf8("LabelPixSpace"))
        self.gridLayout_5.addWidget(self.LabelPixSpace, 2, 0, 1, 2)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 50, 62, 421))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.upperSlider = QtGui.QSlider(self.layoutWidget2)
        self.upperSlider.setOrientation(QtCore.Qt.Vertical)
        self.upperSlider.setInvertedAppearance(True)
        self.upperSlider.setObjectName(_fromUtf8("upperSlider"))
        self.gridLayout.addWidget(self.upperSlider, 0, 0, 1, 1)
        self.lowerSlider = QtGui.QSlider(self.layoutWidget2)
        self.lowerSlider.setOrientation(QtCore.Qt.Vertical)
        self.lowerSlider.setInvertedAppearance(True)
        self.lowerSlider.setObjectName(_fromUtf8("lowerSlider"))
        self.gridLayout.addWidget(self.lowerSlider, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 20, 411, 21))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.LRSlider = QtGui.QSlider(self.layoutWidget3)
        self.LRSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LRSlider.setObjectName(_fromUtf8("LRSlider"))
        self.gridLayout_2.addWidget(self.LRSlider, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(590, 200, 171, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 31, 158, 51))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Button_defineEarpin = QtGui.QPushButton(self.widget)
        self.Button_defineEarpin.setEnabled(True)
        self.Button_defineEarpin.setObjectName(_fromUtf8("Button_defineEarpin"))
        self.gridLayout_3.addWidget(self.Button_defineEarpin, 0, 0, 1, 2)
        self.Button_lockEarpin = QtGui.QPushButton(self.widget)
        self.Button_lockEarpin.setEnabled(True)
        self.Button_lockEarpin.setObjectName(_fromUtf8("Button_lockEarpin"))
        self.gridLayout_3.addWidget(self.Button_lockEarpin, 0, 2, 1, 2)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.TxtEarpinX = QtGui.QDoubleSpinBox(self.widget)
        self.TxtEarpinX.setSingleStep(0.1)
        self.TxtEarpinX.setObjectName(_fromUtf8("TxtEarpinX"))
        self.gridLayout_3.addWidget(self.TxtEarpinX, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 2, 1, 1)
        self.TxtEarpinY = QtGui.QDoubleSpinBox(self.widget)
        self.TxtEarpinY.setSingleStep(0.1)
        self.TxtEarpinY.setObjectName(_fromUtf8("TxtEarpinY"))
        self.gridLayout_3.addWidget(self.TxtEarpinY, 1, 3, 1, 1)
        self.Button_Done = QtGui.QPushButton(self.centralwidget)
        self.Button_Done.setGeometry(QtCore.QRect(590, 310, 171, 31))
        self.Button_Done.setObjectName(_fromUtf8("Button_Done"))
        Landmark.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Landmark)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Landmark.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Landmark)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Landmark.setStatusBar(self.statusbar)

        self.retranslateUi(Landmark)
        QtCore.QMetaObject.connectSlotsByName(Landmark)

    def retranslateUi(self, Landmark):
        Landmark.setWindowTitle(_translate("Landmark", "Landmark Definition", None))
        self.groupBox_autodetect.setTitle(_translate("Landmark", "Bed edges", None))
        self.Button_accptPxSpace.setText(_translate("Landmark", "Lock", None))
        self.Button_defineROI.setText(_translate("Landmark", "Set by ROI", None))
        self.Button_defineMan.setText(_translate("Landmark", "Set manually", None))
        self.label_7.setText(_translate("Landmark", "top edge:", None))
        self.label_8.setText(_translate("Landmark", "bottom edge", None))
        self.LabelPixSpace.setText(_translate("Landmark", "Pixel Spacing:", None))
        self.label.setText(_translate("Landmark", "upper", None))
        self.label_2.setText(_translate("Landmark", "lower", None))
        self.label_3.setText(_translate("Landmark", "LR", None))
        self.groupBox.setTitle(_translate("Landmark", "Earpin", None))
        self.Button_defineEarpin.setText(_translate("Landmark", "Set", None))
        self.Button_lockEarpin.setText(_translate("Landmark", "Lock", None))
        self.label_9.setText(_translate("Landmark", "x=", None))
        self.label_10.setText(_translate("Landmark", "y=", None))
        self.Button_Done.setText(_translate("Landmark", "Done", None))

from matplotlibwidgetFile import matplotlibWidget
