# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Positioning_Assistant_GUI.ui'
#
# Created: Wed Apr 25 10:58:48 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mouse_Positioning_Interface(object):
    def setupUi(self, Mouse_Positioning_Interface):
        Mouse_Positioning_Interface.setObjectName(_fromUtf8("Mouse_Positioning_Interface"))
        Mouse_Positioning_Interface.setEnabled(True)
        Mouse_Positioning_Interface.resize(1412, 894)
        Mouse_Positioning_Interface.setAutoFillBackground(False)
        Mouse_Positioning_Interface.setStyleSheet(_fromUtf8("h"))
        self.centralwidget = QtGui.QWidget(Mouse_Positioning_Interface)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_25 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.XRay_group = QtGui.QGroupBox(self.centralwidget)
        self.XRay_group.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XRay_group.sizePolicy().hasHeightForWidth())
        self.XRay_group.setSizePolicy(sizePolicy)
        self.XRay_group.setMinimumSize(QtCore.QSize(840, 650))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.XRay_group.setFont(font)
        self.XRay_group.setAcceptDrops(False)
        self.XRay_group.setAutoFillBackground(False)
        self.XRay_group.setStyleSheet(_fromUtf8(""))
        self.XRay_group.setFlat(False)
        self.XRay_group.setCheckable(False)
        self.XRay_group.setObjectName(_fromUtf8("XRay_group"))
        self.gridLayout_33 = QtGui.QGridLayout(self.XRay_group)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.XRay_Tabs = QtGui.QTabWidget(self.XRay_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XRay_Tabs.sizePolicy().hasHeightForWidth())
        self.XRay_Tabs.setSizePolicy(sizePolicy)
        self.XRay_Tabs.setMinimumSize(QtCore.QSize(500, 0))
        self.XRay_Tabs.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.XRay_Tabs.setFont(font)
        self.XRay_Tabs.setStyleSheet(_fromUtf8(""))
        self.XRay_Tabs.setTabShape(QtGui.QTabWidget.Triangular)
        self.XRay_Tabs.setObjectName(_fromUtf8("XRay_Tabs"))
        self.Tab_RTStruct = QtGui.QWidget()
        self.Tab_RTStruct.setObjectName(_fromUtf8("Tab_RTStruct"))
        self.gridLayout_13 = QtGui.QGridLayout(self.Tab_RTStruct)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.Tab_RTStruct)
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.Text_XR_Filename = QtGui.QTextEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_XR_Filename.sizePolicy().hasHeightForWidth())
        self.Text_XR_Filename.setSizePolicy(sizePolicy)
        self.Text_XR_Filename.setMinimumSize(QtCore.QSize(130, 40))
        self.Text_XR_Filename.setMaximumSize(QtCore.QSize(10000, 60))
        self.Text_XR_Filename.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_XR_Filename.setObjectName(_fromUtf8("Text_XR_Filename"))
        self.gridLayout_7.addWidget(self.Text_XR_Filename, 1, 0, 1, 1)
        self.Button_LoadRTstruct = QtGui.QPushButton(self.groupBox_7)
        self.Button_LoadRTstruct.setEnabled(True)
        self.Button_LoadRTstruct.setMinimumSize(QtCore.QSize(130, 30))
        self.Button_LoadRTstruct.setMaximumSize(QtCore.QSize(10000, 10000))
        self.Button_LoadRTstruct.setDefault(True)
        self.Button_LoadRTstruct.setFlat(False)
        self.Button_LoadRTstruct.setObjectName(_fromUtf8("Button_LoadRTstruct"))
        self.gridLayout_7.addWidget(self.Button_LoadRTstruct, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_7, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(349, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.Tab_RTStruct)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.LabelPosition = QtGui.QLabel(self.groupBox_2)
        self.LabelPosition.setMinimumSize(QtCore.QSize(200, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelPosition.setFont(font)
        self.LabelPosition.setObjectName(_fromUtf8("LabelPosition"))
        self.gridLayout_16.addWidget(self.LabelPosition, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.TxtXRPinX = QtGui.QLineEdit(self.groupBox_2)
        self.TxtXRPinX.setEnabled(False)
        self.TxtXRPinX.setMinimumSize(QtCore.QSize(50, 0))
        self.TxtXRPinX.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtXRPinX.setFont(font)
        self.TxtXRPinX.setObjectName(_fromUtf8("TxtXRPinX"))
        self.gridLayout_9.addWidget(self.TxtXRPinX, 0, 1, 1, 1)
        self.LabelXRayUnit_2 = QtGui.QLabel(self.groupBox_2)
        self.LabelXRayUnit_2.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelXRayUnit_2.setFont(font)
        self.LabelXRayUnit_2.setText(_fromUtf8(""))
        self.LabelXRayUnit_2.setObjectName(_fromUtf8("LabelXRayUnit_2"))
        self.gridLayout_9.addWidget(self.LabelXRayUnit_2, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_9.addWidget(self.label_12, 0, 3, 1, 1)
        self.TxtXRPinY = QtGui.QLineEdit(self.groupBox_2)
        self.TxtXRPinY.setEnabled(False)
        self.TxtXRPinY.setMinimumSize(QtCore.QSize(50, 0))
        self.TxtXRPinY.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtXRPinY.setFont(font)
        self.TxtXRPinY.setObjectName(_fromUtf8("TxtXRPinY"))
        self.gridLayout_9.addWidget(self.TxtXRPinY, 0, 4, 1, 1)
        self.LabelXRayUnit2_2 = QtGui.QLabel(self.groupBox_2)
        self.LabelXRayUnit2_2.setMinimumSize(QtCore.QSize(15, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelXRayUnit2_2.setFont(font)
        self.LabelXRayUnit2_2.setText(_fromUtf8(""))
        self.LabelXRayUnit2_2.setObjectName(_fromUtf8("LabelXRayUnit2_2"))
        self.gridLayout_9.addWidget(self.LabelXRayUnit2_2, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.TxtTrgtX = QtGui.QLineEdit(self.groupBox_2)
        self.TxtTrgtX.setEnabled(False)
        self.TxtTrgtX.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtTrgtX.setFont(font)
        self.TxtTrgtX.setObjectName(_fromUtf8("TxtTrgtX"))
        self.gridLayout_9.addWidget(self.TxtTrgtX, 1, 1, 1, 1)
        self.LabelXRayUnit = QtGui.QLabel(self.groupBox_2)
        self.LabelXRayUnit.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelXRayUnit.setFont(font)
        self.LabelXRayUnit.setText(_fromUtf8(""))
        self.LabelXRayUnit.setObjectName(_fromUtf8("LabelXRayUnit"))
        self.gridLayout_9.addWidget(self.LabelXRayUnit, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 1, 3, 1, 1)
        self.TxtTrgtY = QtGui.QLineEdit(self.groupBox_2)
        self.TxtTrgtY.setEnabled(False)
        self.TxtTrgtY.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtTrgtY.setFont(font)
        self.TxtTrgtY.setObjectName(_fromUtf8("TxtTrgtY"))
        self.gridLayout_9.addWidget(self.TxtTrgtY, 1, 4, 1, 1)
        self.LabelXRayUnit2 = QtGui.QLabel(self.groupBox_2)
        self.LabelXRayUnit2.setMinimumSize(QtCore.QSize(15, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelXRayUnit2.setFont(font)
        self.LabelXRayUnit2.setText(_fromUtf8(""))
        self.LabelXRayUnit2.setObjectName(_fromUtf8("LabelXRayUnit2"))
        self.gridLayout_9.addWidget(self.LabelXRayUnit2, 1, 5, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.Tab_RTStruct)
        self.groupBox_14.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_39 = QtGui.QLabel(self.groupBox_14)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_17.addWidget(self.label_39, 2, 0, 1, 1)
        self.Txt_Mouse_ID = QtGui.QLabel(self.groupBox_14)
        self.Txt_Mouse_ID.setObjectName(_fromUtf8("Txt_Mouse_ID"))
        self.gridLayout_17.addWidget(self.Txt_Mouse_ID, 0, 1, 1, 1)
        self.Txt_CT_detect_pos = QtGui.QLabel(self.groupBox_14)
        self.Txt_CT_detect_pos.setObjectName(_fromUtf8("Txt_CT_detect_pos"))
        self.gridLayout_17.addWidget(self.Txt_CT_detect_pos, 2, 1, 1, 1)
        self.Txt_CT_date = QtGui.QLabel(self.groupBox_14)
        self.Txt_CT_date.setObjectName(_fromUtf8("Txt_CT_date"))
        self.gridLayout_17.addWidget(self.Txt_CT_date, 1, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_14)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_17.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_14)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_17.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_14, 2, 0, 1, 1)
        self.XRay_Tabs.addTab(self.Tab_RTStruct, _fromUtf8(""))
        self.Tab_PlanarRepos = QtGui.QWidget()
        self.Tab_PlanarRepos.setObjectName(_fromUtf8("Tab_PlanarRepos"))
        self.gridLayout_19 = QtGui.QGridLayout(self.Tab_PlanarRepos)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.TabforScan = QtGui.QTabWidget(self.Tab_PlanarRepos)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TabforScan.setFont(font)
        self.TabforScan.setAutoFillBackground(False)
        self.TabforScan.setTabShape(QtGui.QTabWidget.Triangular)
        self.TabforScan.setObjectName(_fromUtf8("TabforScan"))
        self.Plan = QtGui.QWidget()
        self.Plan.setObjectName(_fromUtf8("Plan"))
        self.gridLayout_31 = QtGui.QGridLayout(self.Plan)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem3, 2, 1, 1, 1)
        self.Display_Plan = matplotlibWidget(self.Plan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Plan.sizePolicy().hasHeightForWidth())
        self.Display_Plan.setSizePolicy(sizePolicy)
        self.Display_Plan.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_Plan.setMaximumSize(QtCore.QSize(400, 400))
        self.Display_Plan.setObjectName(_fromUtf8("Display_Plan"))
        self.gridLayout_31.addWidget(self.Display_Plan, 0, 0, 4, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.Plan)
        self.groupBox_11.setMinimumSize(QtCore.QSize(250, 120))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.Button_Load_Plan = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Load_Plan.sizePolicy().hasHeightForWidth())
        self.Button_Load_Plan.setSizePolicy(sizePolicy)
        self.Button_Load_Plan.setMinimumSize(QtCore.QSize(260, 30))
        self.Button_Load_Plan.setObjectName(_fromUtf8("Button_Load_Plan"))
        self.gridLayout_22.addWidget(self.Button_Load_Plan, 0, 0, 1, 1)
        self.txt_file_Plan = QtGui.QTextBrowser(self.groupBox_11)
        self.txt_file_Plan.setMinimumSize(QtCore.QSize(0, 40))
        self.txt_file_Plan.setMaximumSize(QtCore.QSize(10000, 60))
        self.txt_file_Plan.setObjectName(_fromUtf8("txt_file_Plan"))
        self.gridLayout_22.addWidget(self.txt_file_Plan, 1, 0, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.Plan)
        self.groupBox_9.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_11.addWidget(self.label)
        self.Slider_Plan_GV_center = QtGui.QSlider(self.groupBox_9)
        self.Slider_Plan_GV_center.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Plan_GV_center.setObjectName(_fromUtf8("Slider_Plan_GV_center"))
        self.horizontalLayout_11.addWidget(self.Slider_Plan_GV_center)
        self.Txt_Plan_GV_center = QtGui.QLabel(self.groupBox_9)
        self.Txt_Plan_GV_center.setAutoFillBackground(False)
        self.Txt_Plan_GV_center.setObjectName(_fromUtf8("Txt_Plan_GV_center"))
        self.horizontalLayout_11.addWidget(self.Txt_Plan_GV_center)
        self.gridLayout_23.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_3 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_12.addWidget(self.label_3)
        self.Slider_Plan_GV_range = QtGui.QSlider(self.groupBox_9)
        self.Slider_Plan_GV_range.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Plan_GV_range.setObjectName(_fromUtf8("Slider_Plan_GV_range"))
        self.horizontalLayout_12.addWidget(self.Slider_Plan_GV_range)
        self.Txt_Plan_GV_range = QtGui.QLabel(self.groupBox_9)
        self.Txt_Plan_GV_range.setObjectName(_fromUtf8("Txt_Plan_GV_range"))
        self.horizontalLayout_12.addWidget(self.Txt_Plan_GV_range)
        self.gridLayout_23.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.Display_Plan_Hist = matplotlibWidget(self.groupBox_9)
        self.Display_Plan_Hist.setMinimumSize(QtCore.QSize(160, 80))
        self.Display_Plan_Hist.setObjectName(_fromUtf8("Display_Plan_Hist"))
        self.gridLayout_23.addWidget(self.Display_Plan_Hist, 0, 0, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_9, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem4, 4, 0, 1, 1)
        self.TabforScan.addTab(self.Plan, _fromUtf8(""))
        self.Treatment = QtGui.QWidget()
        self.Treatment.setObjectName(_fromUtf8("Treatment"))
        self.gridLayout_27 = QtGui.QGridLayout(self.Treatment)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem5, 2, 1, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.Treatment)
        self.groupBox_12.setMinimumSize(QtCore.QSize(250, 120))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.Button_Load_Treatment = QtGui.QPushButton(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Load_Treatment.sizePolicy().hasHeightForWidth())
        self.Button_Load_Treatment.setSizePolicy(sizePolicy)
        self.Button_Load_Treatment.setMinimumSize(QtCore.QSize(260, 30))
        self.Button_Load_Treatment.setObjectName(_fromUtf8("Button_Load_Treatment"))
        self.gridLayout_24.addWidget(self.Button_Load_Treatment, 0, 0, 1, 1)
        self.txt_file_Treatment = QtGui.QTextBrowser(self.groupBox_12)
        self.txt_file_Treatment.setMinimumSize(QtCore.QSize(0, 60))
        self.txt_file_Treatment.setMaximumSize(QtCore.QSize(16777215, 60))
        self.txt_file_Treatment.setObjectName(_fromUtf8("txt_file_Treatment"))
        self.gridLayout_24.addWidget(self.txt_file_Treatment, 1, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.Display_Treatment = matplotlibWidget(self.Treatment)
        self.Display_Treatment.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_Treatment.setMaximumSize(QtCore.QSize(400, 400))
        self.Display_Treatment.setObjectName(_fromUtf8("Display_Treatment"))
        self.gridLayout_27.addWidget(self.Display_Treatment, 0, 0, 4, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.Treatment)
        self.groupBox_15.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 260))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.Display_Treatment_Hist = matplotlibWidget(self.groupBox_15)
        self.Display_Treatment_Hist.setMinimumSize(QtCore.QSize(160, 80))
        self.Display_Treatment_Hist.setObjectName(_fromUtf8("Display_Treatment_Hist"))
        self.gridLayout_26.addWidget(self.Display_Treatment_Hist, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_36 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_13.addWidget(self.label_36)
        self.Slider_Treat_GV_center = QtGui.QSlider(self.groupBox_15)
        self.Slider_Treat_GV_center.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Treat_GV_center.setObjectName(_fromUtf8("Slider_Treat_GV_center"))
        self.horizontalLayout_13.addWidget(self.Slider_Treat_GV_center)
        self.Txt_Treat_GV_center = QtGui.QLabel(self.groupBox_15)
        self.Txt_Treat_GV_center.setAutoFillBackground(False)
        self.Txt_Treat_GV_center.setObjectName(_fromUtf8("Txt_Treat_GV_center"))
        self.horizontalLayout_13.addWidget(self.Txt_Treat_GV_center)
        self.gridLayout_26.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_37 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_14.addWidget(self.label_37)
        self.Slider_Treat_GV_range = QtGui.QSlider(self.groupBox_15)
        self.Slider_Treat_GV_range.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Treat_GV_range.setObjectName(_fromUtf8("Slider_Treat_GV_range"))
        self.horizontalLayout_14.addWidget(self.Slider_Treat_GV_range)
        self.Txt_Treat_GV_range = QtGui.QLabel(self.groupBox_15)
        self.Txt_Treat_GV_range.setObjectName(_fromUtf8("Txt_Treat_GV_range"))
        self.horizontalLayout_14.addWidget(self.Txt_Treat_GV_range)
        self.gridLayout_26.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_15, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem6, 4, 1, 1, 1)
        self.TabforScan.addTab(self.Treatment, _fromUtf8(""))
        self.Comparison = QtGui.QWidget()
        self.Comparison.setObjectName(_fromUtf8("Comparison"))
        self.gridLayout_35 = QtGui.QGridLayout(self.Comparison)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.Button_Accept_Repositioning = QtGui.QCommandLinkButton(self.Comparison)
        self.Button_Accept_Repositioning.setEnabled(False)
        self.Button_Accept_Repositioning.setObjectName(_fromUtf8("Button_Accept_Repositioning"))
        self.gridLayout_35.addWidget(self.Button_Accept_Repositioning, 3, 1, 1, 1)
        self.group_move_Overlay_2 = QtGui.QGroupBox(self.Comparison)
        self.group_move_Overlay_2.setEnabled(False)
        self.group_move_Overlay_2.setMinimumSize(QtCore.QSize(150, 0))
        self.group_move_Overlay_2.setMaximumSize(QtCore.QSize(10000, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_move_Overlay_2.setFont(font)
        self.group_move_Overlay_2.setObjectName(_fromUtf8("group_move_Overlay_2"))
        self.gridLayout_32 = QtGui.QGridLayout(self.group_move_Overlay_2)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_46 = QtGui.QLabel(self.group_move_Overlay_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_16.addWidget(self.label_46)
        self.LCD_shift_x = QtGui.QLCDNumber(self.group_move_Overlay_2)
        self.LCD_shift_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCD_shift_x.setObjectName(_fromUtf8("LCD_shift_x"))
        self.horizontalLayout_16.addWidget(self.LCD_shift_x)
        self.label_47 = QtGui.QLabel(self.group_move_Overlay_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_16.addWidget(self.label_47)
        self.gridLayout_32.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_44 = QtGui.QLabel(self.group_move_Overlay_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_15.addWidget(self.label_44)
        self.LCD_shift_y = QtGui.QLCDNumber(self.group_move_Overlay_2)
        self.LCD_shift_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LCD_shift_y.setObjectName(_fromUtf8("LCD_shift_y"))
        self.horizontalLayout_15.addWidget(self.LCD_shift_y)
        self.label_45 = QtGui.QLabel(self.group_move_Overlay_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_15.addWidget(self.label_45)
        self.gridLayout_32.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.gridLayout_35.addWidget(self.group_move_Overlay_2, 2, 1, 1, 1)
        self.group_move_Overlay_3 = QtGui.QGroupBox(self.Comparison)
        self.group_move_Overlay_3.setEnabled(False)
        self.group_move_Overlay_3.setMinimumSize(QtCore.QSize(150, 0))
        self.group_move_Overlay_3.setMaximumSize(QtCore.QSize(10000, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_move_Overlay_3.setFont(font)
        self.group_move_Overlay_3.setObjectName(_fromUtf8("group_move_Overlay_3"))
        self.gridLayout_30 = QtGui.QGridLayout(self.group_move_Overlay_3)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_48 = QtGui.QLabel(self.group_move_Overlay_3)
        self.label_48.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_10.addWidget(self.label_48)
        self.Planar_spacing_x = QtGui.QLCDNumber(self.group_move_Overlay_3)
        self.Planar_spacing_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Planar_spacing_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Planar_spacing_x.setObjectName(_fromUtf8("Planar_spacing_x"))
        self.horizontalLayout_10.addWidget(self.Planar_spacing_x)
        self.label_49 = QtGui.QLabel(self.group_move_Overlay_3)
        self.label_49.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_10.addWidget(self.label_49)
        self.gridLayout_30.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_50 = QtGui.QLabel(self.group_move_Overlay_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_17.addWidget(self.label_50)
        self.Planar_spacing_y = QtGui.QLCDNumber(self.group_move_Overlay_3)
        self.Planar_spacing_y.setMinimumSize(QtCore.QSize(40, 0))
        self.Planar_spacing_y.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Planar_spacing_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Planar_spacing_y.setObjectName(_fromUtf8("Planar_spacing_y"))
        self.horizontalLayout_17.addWidget(self.Planar_spacing_y)
        self.label_51 = QtGui.QLabel(self.group_move_Overlay_3)
        self.label_51.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_17.addWidget(self.label_51)
        self.gridLayout_30.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.gridLayout_35.addWidget(self.group_move_Overlay_3, 1, 1, 1, 1)
        self.group_move_Overlay = QtGui.QGroupBox(self.Comparison)
        self.group_move_Overlay.setEnabled(False)
        self.group_move_Overlay.setMinimumSize(QtCore.QSize(150, 0))
        self.group_move_Overlay.setMaximumSize(QtCore.QSize(100000, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.group_move_Overlay.setFont(font)
        self.group_move_Overlay.setObjectName(_fromUtf8("group_move_Overlay"))
        self.gridLayout_18 = QtGui.QGridLayout(self.group_move_Overlay)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Button_UP = QtGui.QPushButton(self.group_move_Overlay)
        self.Button_UP.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/move_top.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_UP.setIcon(icon)
        self.Button_UP.setObjectName(_fromUtf8("Button_UP"))
        self.gridLayout.addWidget(self.Button_UP, 0, 1, 1, 1)
        self.Button_LEFT = QtGui.QPushButton(self.group_move_Overlay)
        self.Button_LEFT.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/move_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_LEFT.setIcon(icon1)
        self.Button_LEFT.setObjectName(_fromUtf8("Button_LEFT"))
        self.gridLayout.addWidget(self.Button_LEFT, 1, 0, 1, 1)
        self.Button_RESET = QtGui.QPushButton(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Button_RESET.setFont(font)
        self.Button_RESET.setObjectName(_fromUtf8("Button_RESET"))
        self.gridLayout.addWidget(self.Button_RESET, 1, 1, 1, 1)
        self.Button_RIGHT = QtGui.QPushButton(self.group_move_Overlay)
        self.Button_RIGHT.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/move_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_RIGHT.setIcon(icon2)
        self.Button_RIGHT.setObjectName(_fromUtf8("Button_RIGHT"))
        self.gridLayout.addWidget(self.Button_RIGHT, 1, 2, 1, 1)
        self.Button_DOWN = QtGui.QPushButton(self.group_move_Overlay)
        self.Button_DOWN.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/move_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_DOWN.setIcon(icon3)
        self.Button_DOWN.setObjectName(_fromUtf8("Button_DOWN"))
        self.gridLayout.addWidget(self.Button_DOWN, 2, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_30 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout.addWidget(self.label_30)
        self.input_Planar_move = QtGui.QSpinBox(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.input_Planar_move.setFont(font)
        self.input_Planar_move.setObjectName(_fromUtf8("input_Planar_move"))
        self.horizontalLayout.addWidget(self.input_Planar_move)
        self.label_31 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout.addWidget(self.label_31)
        self.gridLayout_18.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_32 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_2.addWidget(self.label_32)
        self.txt_Planar_shift_x = QtGui.QLCDNumber(self.group_move_Overlay)
        self.txt_Planar_shift_x.setFrameShadow(QtGui.QFrame.Sunken)
        self.txt_Planar_shift_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.txt_Planar_shift_x.setObjectName(_fromUtf8("txt_Planar_shift_x"))
        self.horizontalLayout_2.addWidget(self.txt_Planar_shift_x)
        self.label_34 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_2.addWidget(self.label_34)
        self.gridLayout_18.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_33 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_5.addWidget(self.label_33)
        self.txt_Planar_shift_y = QtGui.QLCDNumber(self.group_move_Overlay)
        self.txt_Planar_shift_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.txt_Planar_shift_y.setObjectName(_fromUtf8("txt_Planar_shift_y"))
        self.horizontalLayout_5.addWidget(self.txt_Planar_shift_y)
        self.label_35 = QtGui.QLabel(self.group_move_Overlay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_5.addWidget(self.label_35)
        self.gridLayout_18.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_35.addWidget(self.group_move_Overlay, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem7, 4, 1, 1, 1)
        self.Planar_Scan_Toolbox = QtGui.QToolBox(self.Comparison)
        self.Planar_Scan_Toolbox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Planar_Scan_Toolbox.sizePolicy().hasHeightForWidth())
        self.Planar_Scan_Toolbox.setSizePolicy(sizePolicy)
        self.Planar_Scan_Toolbox.setMinimumSize(QtCore.QSize(570, 400))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Planar_Scan_Toolbox.setFont(font)
        self.Planar_Scan_Toolbox.setStyleSheet(_fromUtf8(""))
        self.Planar_Scan_Toolbox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Planar_Scan_Toolbox.setFrameShadow(QtGui.QFrame.Raised)
        self.Planar_Scan_Toolbox.setObjectName(_fromUtf8("Planar_Scan_Toolbox"))
        self.Overlay = QtGui.QWidget()
        self.Overlay.setGeometry(QtCore.QRect(0, 0, 564, 424))
        self.Overlay.setObjectName(_fromUtf8("Overlay"))
        self.gridLayout_28 = QtGui.QGridLayout(self.Overlay)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        spacerItem8 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem9, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.Overlay)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setStyleSheet(_fromUtf8("QFrame {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_29 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet(_fromUtf8("border: 0px;"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_20.addWidget(self.label_29, 0, 0, 1, 2)
        self.Slider_Planar_Overlay = QtGui.QSlider(self.frame)
        self.Slider_Planar_Overlay.setMinimumSize(QtCore.QSize(0, 20))
        self.Slider_Planar_Overlay.setMaximum(100)
        self.Slider_Planar_Overlay.setSliderPosition(50)
        self.Slider_Planar_Overlay.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Planar_Overlay.setObjectName(_fromUtf8("Slider_Planar_Overlay"))
        self.gridLayout_20.addWidget(self.Slider_Planar_Overlay, 1, 0, 1, 2)
        self.label_27 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("border: 0px;"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_20.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("border: 0px;"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_20.addWidget(self.label_28, 2, 1, 1, 1)
        self.gridLayout_28.addWidget(self.frame, 0, 1, 1, 1)
        self.Display_Overlay = matplotlibWidget(self.Overlay)
        self.Display_Overlay.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_Overlay.setMaximumSize(QtCore.QSize(400, 400))
        self.Display_Overlay.setObjectName(_fromUtf8("Display_Overlay"))
        self.gridLayout_28.addWidget(self.Display_Overlay, 0, 0, 2, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.Overlay)
        self.groupBox_16.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.Display_Overlay_Hist = matplotlibWidget(self.groupBox_16)
        self.Display_Overlay_Hist.setMinimumSize(QtCore.QSize(100, 80))
        self.Display_Overlay_Hist.setObjectName(_fromUtf8("Display_Overlay_Hist"))
        self.gridLayout_21.addWidget(self.Display_Overlay_Hist, 0, 0, 1, 3)
        self.label_40 = QtGui.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_21.addWidget(self.label_40, 1, 0, 1, 1)
        self.Slider_Overlay_GV_center = QtGui.QSlider(self.groupBox_16)
        self.Slider_Overlay_GV_center.setMinimumSize(QtCore.QSize(0, 20))
        self.Slider_Overlay_GV_center.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Overlay_GV_center.setObjectName(_fromUtf8("Slider_Overlay_GV_center"))
        self.gridLayout_21.addWidget(self.Slider_Overlay_GV_center, 1, 1, 1, 1)
        self.Txt_Overlay_GV_center = QtGui.QLabel(self.groupBox_16)
        self.Txt_Overlay_GV_center.setAutoFillBackground(False)
        self.Txt_Overlay_GV_center.setObjectName(_fromUtf8("Txt_Overlay_GV_center"))
        self.gridLayout_21.addWidget(self.Txt_Overlay_GV_center, 1, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_21.addWidget(self.label_41, 2, 0, 1, 1)
        self.Slider_Overlay_GV_range = QtGui.QSlider(self.groupBox_16)
        self.Slider_Overlay_GV_range.setMinimumSize(QtCore.QSize(0, 20))
        self.Slider_Overlay_GV_range.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Overlay_GV_range.setObjectName(_fromUtf8("Slider_Overlay_GV_range"))
        self.gridLayout_21.addWidget(self.Slider_Overlay_GV_range, 2, 1, 1, 1)
        self.Txt_Overlay_GV_range = QtGui.QLabel(self.groupBox_16)
        self.Txt_Overlay_GV_range.setObjectName(_fromUtf8("Txt_Overlay_GV_range"))
        self.gridLayout_21.addWidget(self.Txt_Overlay_GV_range, 2, 2, 1, 1)
        self.gridLayout_28.addWidget(self.groupBox_16, 1, 1, 1, 1)
        self.Planar_Scan_Toolbox.addItem(self.Overlay, _fromUtf8(""))
        self.False_Color = QtGui.QWidget()
        self.False_Color.setGeometry(QtCore.QRect(0, 0, 581, 447))
        self.False_Color.setObjectName(_fromUtf8("False_Color"))
        self.gridLayout_38 = QtGui.QGridLayout(self.False_Color)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem10, 3, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem11, 4, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem12, 0, 2, 1, 1)
        self.frame_2 = QtGui.QFrame(self.False_Color)
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_29 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.label_61 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_29.addWidget(self.label_61, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.False_Color)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_37 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.label_62 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_37.addWidget(self.label_62, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.frame_3, 1, 1, 1, 1)
        self.Display_FalseColor = matplotlibWidget(self.False_Color)
        self.Display_FalseColor.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_FalseColor.sizePolicy().hasHeightForWidth())
        self.Display_FalseColor.setSizePolicy(sizePolicy)
        self.Display_FalseColor.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_FalseColor.setMaximumSize(QtCore.QSize(400, 400))
        self.Display_FalseColor.setObjectName(_fromUtf8("Display_FalseColor"))
        self.gridLayout_38.addWidget(self.Display_FalseColor, 0, 0, 4, 1)
        self.label_63 = QtGui.QLabel(self.False_Color)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setFrameShape(QtGui.QFrame.Panel)
        self.label_63.setFrameShadow(QtGui.QFrame.Raised)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_38.addWidget(self.label_63, 2, 1, 1, 1)
        self.Planar_Scan_Toolbox.addItem(self.False_Color, _fromUtf8(""))
        self.Difference = QtGui.QWidget()
        self.Difference.setGeometry(QtCore.QRect(0, 0, 564, 424))
        self.Difference.setObjectName(_fromUtf8("Difference"))
        self.gridLayout_12 = QtGui.QGridLayout(self.Difference)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.Display_Difference = matplotlibWidget(self.Difference)
        self.Display_Difference.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Difference.sizePolicy().hasHeightForWidth())
        self.Display_Difference.setSizePolicy(sizePolicy)
        self.Display_Difference.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_Difference.setMaximumSize(QtCore.QSize(400, 400))
        self.Display_Difference.setObjectName(_fromUtf8("Display_Difference"))
        self.gridLayout_12.addWidget(self.Display_Difference, 0, 0, 2, 1)
        self.groupBox_17 = QtGui.QGroupBox(self.Difference)
        self.groupBox_17.setMinimumSize(QtCore.QSize(140, 200))
        self.groupBox_17.setMaximumSize(QtCore.QSize(16777215, 100000))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_17)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Display_Difference_Hist = matplotlibWidget(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Difference_Hist.sizePolicy().hasHeightForWidth())
        self.Display_Difference_Hist.setSizePolicy(sizePolicy)
        self.Display_Difference_Hist.setMinimumSize(QtCore.QSize(100, 80))
        self.Display_Difference_Hist.setObjectName(_fromUtf8("Display_Difference_Hist"))
        self.gridLayout_10.addWidget(self.Display_Difference_Hist, 0, 0, 1, 3)
        self.label_42 = QtGui.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 1, 0, 1, 1)
        self.Slider_Difference_GV_center = QtGui.QSlider(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_Difference_GV_center.sizePolicy().hasHeightForWidth())
        self.Slider_Difference_GV_center.setSizePolicy(sizePolicy)
        self.Slider_Difference_GV_center.setMinimumSize(QtCore.QSize(20, 20))
        self.Slider_Difference_GV_center.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slider_Difference_GV_center.setMaximum(100)
        self.Slider_Difference_GV_center.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Difference_GV_center.setObjectName(_fromUtf8("Slider_Difference_GV_center"))
        self.gridLayout_10.addWidget(self.Slider_Difference_GV_center, 1, 1, 1, 1)
        self.Txt_Difference_GV_center = QtGui.QLabel(self.groupBox_17)
        self.Txt_Difference_GV_center.setMinimumSize(QtCore.QSize(30, 0))
        self.Txt_Difference_GV_center.setAutoFillBackground(False)
        self.Txt_Difference_GV_center.setObjectName(_fromUtf8("Txt_Difference_GV_center"))
        self.gridLayout_10.addWidget(self.Txt_Difference_GV_center, 1, 2, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_10.addWidget(self.label_43, 2, 0, 1, 1)
        self.Slider_Difference_GV_range = QtGui.QSlider(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_Difference_GV_range.sizePolicy().hasHeightForWidth())
        self.Slider_Difference_GV_range.setSizePolicy(sizePolicy)
        self.Slider_Difference_GV_range.setMinimumSize(QtCore.QSize(41, 20))
        self.Slider_Difference_GV_range.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slider_Difference_GV_range.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Difference_GV_range.setObjectName(_fromUtf8("Slider_Difference_GV_range"))
        self.gridLayout_10.addWidget(self.Slider_Difference_GV_range, 2, 1, 1, 1)
        self.Txt_Difference_GV_range = QtGui.QLabel(self.groupBox_17)
        self.Txt_Difference_GV_range.setMinimumSize(QtCore.QSize(30, 0))
        self.Txt_Difference_GV_range.setObjectName(_fromUtf8("Txt_Difference_GV_range"))
        self.gridLayout_10.addWidget(self.Txt_Difference_GV_range, 2, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_17, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(17, 54, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem14, 1, 1, 1, 1)
        self.Planar_Scan_Toolbox.addItem(self.Difference, _fromUtf8(""))
        self.gridLayout_35.addWidget(self.Planar_Scan_Toolbox, 0, 0, 5, 1)
        self.TabforScan.addTab(self.Comparison, _fromUtf8(""))
        self.gridLayout_19.addWidget(self.TabforScan, 0, 0, 1, 1)
        self.XRay_Tabs.addTab(self.Tab_PlanarRepos, _fromUtf8(""))
        self.gridLayout_33.addWidget(self.XRay_Tabs, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.XRay_group, 0, 1, 1, 2)
        self.Radiography_group = QtGui.QGroupBox(self.centralwidget)
        self.Radiography_group.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Radiography_group.setFont(font)
        self.Radiography_group.setAutoFillBackground(False)
        self.Radiography_group.setStyleSheet(_fromUtf8(""))
        self.Radiography_group.setObjectName(_fromUtf8("Radiography_group"))
        self.gridLayout_34 = QtGui.QGridLayout(self.Radiography_group)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.Display_Radiography = matplotlibWidget(self.Radiography_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Radiography.sizePolicy().hasHeightForWidth())
        self.Display_Radiography.setSizePolicy(sizePolicy)
        self.Display_Radiography.setMinimumSize(QtCore.QSize(300, 300))
        self.Display_Radiography.setObjectName(_fromUtf8("Display_Radiography"))
        self.gridLayout_34.addWidget(self.Display_Radiography, 0, 0, 1, 2)
        self.Group_FieldLimits = QtGui.QGroupBox(self.Radiography_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Group_FieldLimits.setFont(font)
        self.Group_FieldLimits.setObjectName(_fromUtf8("Group_FieldLimits"))
        self.gridLayout_15 = QtGui.QGridLayout(self.Group_FieldLimits)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_15 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_15.addWidget(self.label_15, 0, 0, 1, 1)
        self.x_Left = QtGui.QLineEdit(self.Group_FieldLimits)
        self.x_Left.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_Left.setFont(font)
        self.x_Left.setReadOnly(True)
        self.x_Left.setObjectName(_fromUtf8("x_Left"))
        self.gridLayout_15.addWidget(self.x_Left, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_15.addWidget(self.label_17, 0, 2, 1, 1)
        self.x_Right = QtGui.QLineEdit(self.Group_FieldLimits)
        self.x_Right.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_Right.setFont(font)
        self.x_Right.setReadOnly(True)
        self.x_Right.setObjectName(_fromUtf8("x_Right"))
        self.gridLayout_15.addWidget(self.x_Right, 0, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_15.addWidget(self.label_18, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_15.addWidget(self.label_16, 1, 0, 1, 1)
        self.y_top = QtGui.QLineEdit(self.Group_FieldLimits)
        self.y_top.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_top.setFont(font)
        self.y_top.setReadOnly(True)
        self.y_top.setObjectName(_fromUtf8("y_top"))
        self.gridLayout_15.addWidget(self.y_top, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_15.addWidget(self.label_19, 1, 2, 1, 1)
        self.y_bottom = QtGui.QLineEdit(self.Group_FieldLimits)
        self.y_bottom.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_bottom.setFont(font)
        self.y_bottom.setReadOnly(True)
        self.y_bottom.setObjectName(_fromUtf8("y_bottom"))
        self.gridLayout_15.addWidget(self.y_bottom, 1, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.Group_FieldLimits)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_15.addWidget(self.label_20, 1, 4, 1, 1)
        self.gridLayout_34.addWidget(self.Group_FieldLimits, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.Radiography_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.Button_RadiographyLM = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_RadiographyLM.sizePolicy().hasHeightForWidth())
        self.Button_RadiographyLM.setSizePolicy(sizePolicy)
        self.Button_RadiographyLM.setMinimumSize(QtCore.QSize(100, 0))
        self.Button_RadiographyLM.setAutoFillBackground(False)
        self.Button_RadiographyLM.setDefault(True)
        self.Button_RadiographyLM.setObjectName(_fromUtf8("Button_RadiographyLM"))
        self.gridLayout_14.addWidget(self.Button_RadiographyLM, 0, 0, 1, 2)
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_14.addWidget(self.label_24, 1, 0, 1, 1)
        self.TxtRGPinX = QtGui.QLineEdit(self.groupBox_3)
        self.TxtRGPinX.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TxtRGPinX.sizePolicy().hasHeightForWidth())
        self.TxtRGPinX.setSizePolicy(sizePolicy)
        self.TxtRGPinX.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtRGPinX.setFont(font)
        self.TxtRGPinX.setText(_fromUtf8(""))
        self.TxtRGPinX.setObjectName(_fromUtf8("TxtRGPinX"))
        self.gridLayout_14.addWidget(self.TxtRGPinX, 1, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_14.addWidget(self.label_23, 1, 3, 1, 1)
        self.TxtRGPinY = QtGui.QLineEdit(self.groupBox_3)
        self.TxtRGPinY.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TxtRGPinY.sizePolicy().hasHeightForWidth())
        self.TxtRGPinY.setSizePolicy(sizePolicy)
        self.TxtRGPinY.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtRGPinY.setFont(font)
        self.TxtRGPinY.setText(_fromUtf8(""))
        self.TxtRGPinY.setObjectName(_fromUtf8("TxtRGPinY"))
        self.gridLayout_14.addWidget(self.TxtRGPinY, 1, 4, 1, 1)
        self.Button_toggleLandmarksRG = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_toggleLandmarksRG.sizePolicy().hasHeightForWidth())
        self.Button_toggleLandmarksRG.setSizePolicy(sizePolicy)
        self.Button_toggleLandmarksRG.setMinimumSize(QtCore.QSize(80, 0))
        self.Button_toggleLandmarksRG.setAutoFillBackground(False)
        self.Button_toggleLandmarksRG.setDefault(True)
        self.Button_toggleLandmarksRG.setObjectName(_fromUtf8("Button_toggleLandmarksRG"))
        self.gridLayout_14.addWidget(self.Button_toggleLandmarksRG, 0, 2, 1, 3)
        self.gridLayout_34.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.Radiography_group)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Button_LoadRadiography = QtGui.QPushButton(self.groupBox)
        self.Button_LoadRadiography.setEnabled(False)
        self.Button_LoadRadiography.setDefault(True)
        self.Button_LoadRadiography.setFlat(False)
        self.Button_LoadRadiography.setObjectName(_fromUtf8("Button_LoadRadiography"))
        self.gridLayout_3.addWidget(self.Button_LoadRadiography, 0, 0, 1, 1)
        self.Text_RG_Filename = QtGui.QTextEdit(self.groupBox)
        self.Text_RG_Filename.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Text_RG_Filename.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_RG_Filename.setObjectName(_fromUtf8("Text_RG_Filename"))
        self.gridLayout_3.addWidget(self.Text_RG_Filename, 1, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox, 2, 0, 1, 1)
        self.Group_IsoCenter = QtGui.QGroupBox(self.Radiography_group)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Group_IsoCenter.setFont(font)
        self.Group_IsoCenter.setObjectName(_fromUtf8("Group_IsoCenter"))
        self.gridLayout_5 = QtGui.QGridLayout(self.Group_IsoCenter)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.Button_RG_defineIsoCenter = QtGui.QPushButton(self.Group_IsoCenter)
        self.Button_RG_defineIsoCenter.setObjectName(_fromUtf8("Button_RG_defineIsoCenter"))
        self.gridLayout_5.addWidget(self.Button_RG_defineIsoCenter, 0, 0, 1, 2)
        self.Button_Radiograph_toggleIso = QtGui.QPushButton(self.Group_IsoCenter)
        self.Button_Radiograph_toggleIso.setObjectName(_fromUtf8("Button_Radiograph_toggleIso"))
        self.gridLayout_5.addWidget(self.Button_Radiograph_toggleIso, 0, 2, 1, 2)
        self.label_5 = QtGui.QLabel(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.SpotTxt_x = QtGui.QLineEdit(self.Group_IsoCenter)
        self.SpotTxt_x.setMinimumSize(QtCore.QSize(40, 0))
        self.SpotTxt_x.setObjectName(_fromUtf8("SpotTxt_x"))
        self.gridLayout_5.addWidget(self.SpotTxt_x, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 1, 2, 1, 1)
        self.SpotTxt_y = QtGui.QLineEdit(self.Group_IsoCenter)
        self.SpotTxt_y.setEnabled(True)
        self.SpotTxt_y.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpotTxt_y.setFont(font)
        self.SpotTxt_y.setReadOnly(True)
        self.SpotTxt_y.setObjectName(_fromUtf8("SpotTxt_y"))
        self.gridLayout_5.addWidget(self.SpotTxt_y, 1, 3, 1, 1)
        self.gridLayout_34.addWidget(self.Group_IsoCenter, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.Radiography_group, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_36 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_8.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_55 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_6.addWidget(self.label_55, 1, 2, 1, 1)
        self.TxtXRShiftX = QtGui.QLineEdit(self.groupBox_8)
        self.TxtXRShiftX.setEnabled(False)
        self.TxtXRShiftX.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TxtXRShiftX.setFont(font)
        self.TxtXRShiftX.setObjectName(_fromUtf8("TxtXRShiftX"))
        self.gridLayout_6.addWidget(self.TxtXRShiftX, 1, 1, 1, 1)
        self.TxtXRShiftY = QtGui.QLineEdit(self.groupBox_8)
        self.TxtXRShiftY.setEnabled(False)
        self.TxtXRShiftY.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TxtXRShiftY.setFont(font)
        self.TxtXRShiftY.setObjectName(_fromUtf8("TxtXRShiftY"))
        self.gridLayout_6.addWidget(self.TxtXRShiftY, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_6.addWidget(self.label_56, 2, 2, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem15, 2, 3, 1, 1)
        self.LabelPixSpacingXR = QtGui.QLabel(self.groupBox_8)
        self.LabelPixSpacingXR.setMinimumSize(QtCore.QSize(200, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelPixSpacingXR.setFont(font)
        self.LabelPixSpacingXR.setObjectName(_fromUtf8("LabelPixSpacingXR"))
        self.gridLayout_6.addWidget(self.LabelPixSpacingXR, 0, 0, 1, 4)
        self.gridLayout_36.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox_10.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAutoFillBackground(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.TableTxt_x = QtGui.QLineEdit(self.groupBox_10)
        self.TableTxt_x.setEnabled(False)
        self.TableTxt_x.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableTxt_x.setFont(font)
        self.TableTxt_x.setObjectName(_fromUtf8("TableTxt_x"))
        self.gridLayout_2.addWidget(self.TableTxt_x, 1, 1, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_2.addWidget(self.label_57, 1, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.TableTxt_y = QtGui.QLineEdit(self.groupBox_10)
        self.TableTxt_y.setEnabled(False)
        self.TableTxt_y.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableTxt_y.setFont(font)
        self.TableTxt_y.setObjectName(_fromUtf8("TableTxt_y"))
        self.gridLayout_2.addWidget(self.TableTxt_y, 2, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_2.addWidget(self.label_58, 2, 2, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_10, 0, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_53 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_4.addWidget(self.label_53, 1, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_4.addWidget(self.label_52, 1, 0, 1, 1)
        self.TxtRG_pxcalc = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtRG_pxcalc.setFont(font)
        self.TxtRG_pxcalc.setObjectName(_fromUtf8("TxtRG_pxcalc"))
        self.gridLayout_4.addWidget(self.TxtRG_pxcalc, 0, 0, 1, 2)
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 2, 0, 1, 1)
        self.TxtRGShiftX = QtGui.QLineEdit(self.groupBox_5)
        self.TxtRGShiftX.setEnabled(False)
        self.TxtRGShiftX.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TxtRGShiftX.setFont(font)
        self.TxtRGShiftX.setObjectName(_fromUtf8("TxtRGShiftX"))
        self.gridLayout_4.addWidget(self.TxtRGShiftX, 1, 1, 1, 1)
        self.TxtRGShiftY = QtGui.QLineEdit(self.groupBox_5)
        self.TxtRGShiftY.setEnabled(False)
        self.TxtRGShiftY.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TxtRGShiftY.setFont(font)
        self.TxtRGShiftY.setObjectName(_fromUtf8("TxtRGShiftY"))
        self.gridLayout_4.addWidget(self.TxtRGShiftY, 2, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 3, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_4.addWidget(self.label_54, 2, 2, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.Group_Result = QtGui.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Group_Result.setFont(font)
        self.Group_Result.setObjectName(_fromUtf8("Group_Result"))
        self.gridLayout_8 = QtGui.QGridLayout(self.Group_Result)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.TableTxt_yCorr = QtGui.QLineEdit(self.Group_Result)
        self.TableTxt_yCorr.setEnabled(False)
        self.TableTxt_yCorr.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableTxt_yCorr.setFont(font)
        self.TableTxt_yCorr.setObjectName(_fromUtf8("TableTxt_yCorr"))
        self.gridLayout_8.addWidget(self.TableTxt_yCorr, 2, 1, 1, 1)
        self.label_60 = QtGui.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_8.addWidget(self.label_60, 2, 2, 1, 1)
        self.label_59 = QtGui.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_8.addWidget(self.label_59, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 2, 0, 1, 1)
        self.TableTxt_xCorr = QtGui.QLineEdit(self.Group_Result)
        self.TableTxt_xCorr.setEnabled(False)
        self.TableTxt_xCorr.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableTxt_xCorr.setFont(font)
        self.TableTxt_xCorr.setObjectName(_fromUtf8("TableTxt_xCorr"))
        self.gridLayout_8.addWidget(self.TableTxt_xCorr, 1, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 1, 3, 1, 1)
        self.gridLayout_36.addWidget(self.Group_Result, 0, 3, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_36.addItem(spacerItem19, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_4, 1, 0, 4, 2)
        self.Button_LogFile = QtGui.QPushButton(self.centralwidget)
        self.Button_LogFile.setMinimumSize(QtCore.QSize(0, 30))
        self.Button_LogFile.setObjectName(_fromUtf8("Button_LogFile"))
        self.gridLayout_25.addWidget(self.Button_LogFile, 1, 2, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem20, 3, 2, 1, 1)
        self.Button_Exit = QtGui.QPushButton(self.centralwidget)
        self.Button_Exit.setMinimumSize(QtCore.QSize(220, 30))
        self.Button_Exit.setMaximumSize(QtCore.QSize(220, 60))
        self.Button_Exit.setObjectName(_fromUtf8("Button_Exit"))
        self.gridLayout_25.addWidget(self.Button_Exit, 2, 2, 1, 1)
        Mouse_Positioning_Interface.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Mouse_Positioning_Interface)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Mouse_Positioning_Interface.setStatusBar(self.statusbar)
        self.actionLoad_Radiography_scatter = QtGui.QAction(Mouse_Positioning_Interface)
        self.actionLoad_Radiography_scatter.setObjectName(_fromUtf8("actionLoad_Radiography_scatter"))

        self.retranslateUi(Mouse_Positioning_Interface)
        self.XRay_Tabs.setCurrentIndex(1)
        self.TabforScan.setCurrentIndex(2)
        self.Planar_Scan_Toolbox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mouse_Positioning_Interface)

    def retranslateUi(self, Mouse_Positioning_Interface):
        Mouse_Positioning_Interface.setWindowTitle(_translate("Mouse_Positioning_Interface", "Mouse Positioning Interface", None))
        self.XRay_group.setTitle(_translate("Mouse_Positioning_Interface", "X-Ray", None))
        self.groupBox_7.setTitle(_translate("Mouse_Positioning_Interface", "Plan import", None))
        self.Button_LoadRTstruct.setText(_translate("Mouse_Positioning_Interface", "Load RT Structure Set", None))
        self.groupBox_2.setTitle(_translate("Mouse_Positioning_Interface", "Coordinates", None))
        self.LabelPosition.setText(_translate("Mouse_Positioning_Interface", "Patient Position: ", None))
        self.label_11.setText(_translate("Mouse_Positioning_Interface", "x<sub>Pin</sub>=", None))
        self.label_12.setText(_translate("Mouse_Positioning_Interface", "y<sub>Pin</sub>=", None))
        self.label_7.setText(_translate("Mouse_Positioning_Interface", "x<sub>Target</sub>=", None))
        self.label_8.setText(_translate("Mouse_Positioning_Interface", "y<sub>target</sub>=", None))
        self.groupBox_14.setTitle(_translate("Mouse_Positioning_Interface", "Metadata", None))
        self.label_39.setText(_translate("Mouse_Positioning_Interface", "Detector pos.:", None))
        self.Txt_Mouse_ID.setText(_translate("Mouse_Positioning_Interface", "TextLabel", None))
        self.Txt_CT_detect_pos.setText(_translate("Mouse_Positioning_Interface", "TextLabel", None))
        self.Txt_CT_date.setText(_translate("Mouse_Positioning_Interface", "TextLabel", None))
        self.label_38.setText(_translate("Mouse_Positioning_Interface", "CT date:", None))
        self.label_21.setText(_translate("Mouse_Positioning_Interface", "Mouse Number:", None))
        self.XRay_Tabs.setTabText(self.XRay_Tabs.indexOf(self.Tab_RTStruct), _translate("Mouse_Positioning_Interface", "CT Plan Data", None))
        self.groupBox_11.setTitle(_translate("Mouse_Positioning_Interface", "File", None))
        self.Button_Load_Plan.setText(_translate("Mouse_Positioning_Interface", "Load File", None))
        self.groupBox_9.setTitle(_translate("Mouse_Positioning_Interface", "Windowing", None))
        self.label.setText(_translate("Mouse_Positioning_Interface", "Center", None))
        self.Txt_Plan_GV_center.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.label_3.setText(_translate("Mouse_Positioning_Interface", "Range", None))
        self.Txt_Plan_GV_range.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.TabforScan.setTabText(self.TabforScan.indexOf(self.Plan), _translate("Mouse_Positioning_Interface", "Plan", None))
        self.groupBox_12.setTitle(_translate("Mouse_Positioning_Interface", "File", None))
        self.Button_Load_Treatment.setText(_translate("Mouse_Positioning_Interface", "Load File", None))
        self.groupBox_15.setTitle(_translate("Mouse_Positioning_Interface", "Windowing", None))
        self.label_36.setText(_translate("Mouse_Positioning_Interface", "Center", None))
        self.Txt_Treat_GV_center.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.label_37.setText(_translate("Mouse_Positioning_Interface", "Range", None))
        self.Txt_Treat_GV_range.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.TabforScan.setTabText(self.TabforScan.indexOf(self.Treatment), _translate("Mouse_Positioning_Interface", "Treatment", None))
        self.Button_Accept_Repositioning.setText(_translate("Mouse_Positioning_Interface", "Accept", None))
        self.group_move_Overlay_2.setTitle(_translate("Mouse_Positioning_Interface", "Spatial Shift", None))
        self.label_46.setText(_translate("Mouse_Positioning_Interface", "x_Shift =", None))
        self.label_47.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.label_44.setText(_translate("Mouse_Positioning_Interface", "y_Shift =", None))
        self.label_45.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.group_move_Overlay_3.setTitle(_translate("Mouse_Positioning_Interface", "Spacing", None))
        self.label_48.setText(_translate("Mouse_Positioning_Interface", "x:", None))
        self.label_49.setText(_translate("Mouse_Positioning_Interface", "mm/Pixel", None))
        self.label_50.setText(_translate("Mouse_Positioning_Interface", "y:", None))
        self.label_51.setText(_translate("Mouse_Positioning_Interface", "mm/Pixel", None))
        self.group_move_Overlay.setTitle(_translate("Mouse_Positioning_Interface", "Move Image", None))
        self.Button_RESET.setText(_translate("Mouse_Positioning_Interface", "RESET", None))
        self.label_30.setText(_translate("Mouse_Positioning_Interface", "Move by:", None))
        self.label_31.setText(_translate("Mouse_Positioning_Interface", "Pixels", None))
        self.label_32.setText(_translate("Mouse_Positioning_Interface", "x_Shift =", None))
        self.label_34.setText(_translate("Mouse_Positioning_Interface", "Pixels", None))
        self.label_33.setText(_translate("Mouse_Positioning_Interface", "y_Shift =", None))
        self.label_35.setText(_translate("Mouse_Positioning_Interface", "Pixels", None))
        self.label_29.setText(_translate("Mouse_Positioning_Interface", "Move Slider to adjust transparency:", None))
        self.label_27.setText(_translate("Mouse_Positioning_Interface", "0% Plan \n"
"100% Treatment", None))
        self.label_28.setText(_translate("Mouse_Positioning_Interface", "100% Plan \n"
"0% Treatment", None))
        self.groupBox_16.setTitle(_translate("Mouse_Positioning_Interface", "Windowing", None))
        self.label_40.setText(_translate("Mouse_Positioning_Interface", "Center", None))
        self.Txt_Overlay_GV_center.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.label_41.setText(_translate("Mouse_Positioning_Interface", "Range", None))
        self.Txt_Overlay_GV_range.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.Planar_Scan_Toolbox.setItemText(self.Planar_Scan_Toolbox.indexOf(self.Overlay), _translate("Mouse_Positioning_Interface", "Overlay", None))
        self.label_61.setText(_translate("Mouse_Positioning_Interface", "<html><head/><body><p><span style=\" color:#ff0000;\">RED: </span></p><p><span style=\" color:#ff0000;\">Plan image </span></p></body></html>", None))
        self.label_62.setText(_translate("Mouse_Positioning_Interface", "<html><head/><body><p><span style=\" color:#00ff00;\">GREEN: </span></p><p><span style=\" color:#00ff00;\">Treatment image </span></p></body></html>", None))
        self.label_63.setText(_translate("Mouse_Positioning_Interface", "<html><head/><body><p><span style=\" color:#ffffff;\">Use arrows to move </span></p><p><span style=\" color:#ffffff;\">treatment image</span></p></body></html>", None))
        self.Planar_Scan_Toolbox.setItemText(self.Planar_Scan_Toolbox.indexOf(self.False_Color), _translate("Mouse_Positioning_Interface", "False Colors", None))
        self.groupBox_17.setTitle(_translate("Mouse_Positioning_Interface", "Windowing", None))
        self.label_42.setText(_translate("Mouse_Positioning_Interface", "Center", None))
        self.Txt_Difference_GV_center.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.label_43.setText(_translate("Mouse_Positioning_Interface", "Range", None))
        self.Txt_Difference_GV_range.setText(_translate("Mouse_Positioning_Interface", "0", None))
        self.Planar_Scan_Toolbox.setItemText(self.Planar_Scan_Toolbox.indexOf(self.Difference), _translate("Mouse_Positioning_Interface", "Difference", None))
        self.TabforScan.setTabText(self.TabforScan.indexOf(self.Comparison), _translate("Mouse_Positioning_Interface", "Comparison", None))
        self.XRay_Tabs.setTabText(self.XRay_Tabs.indexOf(self.Tab_PlanarRepos), _translate("Mouse_Positioning_Interface", "Repositioning Scan", None))
        self.Radiography_group.setTitle(_translate("Mouse_Positioning_Interface", "Radiography", None))
        self.Group_FieldLimits.setTitle(_translate("Mouse_Positioning_Interface", "Field Limits", None))
        self.label_15.setText(_translate("Mouse_Positioning_Interface", "Field Limits: x = [", None))
        self.label_17.setText(_translate("Mouse_Positioning_Interface", ";", None))
        self.label_18.setText(_translate("Mouse_Positioning_Interface", "]", None))
        self.label_16.setText(_translate("Mouse_Positioning_Interface", "                    y = [", None))
        self.label_19.setText(_translate("Mouse_Positioning_Interface", ";", None))
        self.label_20.setText(_translate("Mouse_Positioning_Interface", "]", None))
        self.groupBox_3.setTitle(_translate("Mouse_Positioning_Interface", "Landmarks", None))
        self.Button_RadiographyLM.setText(_translate("Mouse_Positioning_Interface", "Set Landmarks", None))
        self.label_24.setText(_translate("Mouse_Positioning_Interface", "x<sub>Pin</sub>=", None))
        self.label_23.setText(_translate("Mouse_Positioning_Interface", "y<sub>Pin</sub>=", None))
        self.Button_toggleLandmarksRG.setText(_translate("Mouse_Positioning_Interface", "Toggle Landmarks", None))
        self.groupBox.setTitle(_translate("Mouse_Positioning_Interface", "Object Radiography", None))
        self.Button_LoadRadiography.setText(_translate("Mouse_Positioning_Interface", "Load Radiography (scatter)", None))
        self.Group_IsoCenter.setTitle(_translate("Mouse_Positioning_Interface", "IsoCenter & Field", None))
        self.Button_RG_defineIsoCenter.setText(_translate("Mouse_Positioning_Interface", "Define Field and IsoCenter", None))
        self.Button_Radiograph_toggleIso.setText(_translate("Mouse_Positioning_Interface", "Toggle IsoCenter", None))
        self.label_5.setText(_translate("Mouse_Positioning_Interface", "x<sub>Iso</sub>=", None))
        self.label_6.setText(_translate("Mouse_Positioning_Interface", "y<sub>Iso</sub>=", None))
        self.groupBox_4.setTitle(_translate("Mouse_Positioning_Interface", "Coordinates", None))
        self.groupBox_8.setTitle(_translate("Mouse_Positioning_Interface", "Pin2Target", None))
        self.label_55.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.label_22.setText(_translate("Mouse_Positioning_Interface", "dy=", None))
        self.label_25.setText(_translate("Mouse_Positioning_Interface", "dx=", None))
        self.label_56.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.LabelPixSpacingXR.setText(_translate("Mouse_Positioning_Interface", "Pixel spacing: ", None))
        self.groupBox_10.setTitle(_translate("Mouse_Positioning_Interface", "Object movement table", None))
        self.label_2.setText(_translate("Mouse_Positioning_Interface", "Radiography table position (origin)", None))
        self.label_13.setText(_translate("Mouse_Positioning_Interface", "x_Table=", None))
        self.label_57.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.label_14.setText(_translate("Mouse_Positioning_Interface", "y_Table=", None))
        self.label_58.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.groupBox_5.setToolTip(_translate("Mouse_Positioning_Interface", "These values give the distance in mm between the Earpin and the Beam Isocenter. \n"
"If this distance is to be minimized, the values can be used for realtive positioning in OWIS. \n"
"CAUTION: x-values need to be inverted!", None))
        self.groupBox_5.setTitle(_translate("Mouse_Positioning_Interface", "Pin2 IsoCenter", None))
        self.label_53.setText(_translate("Mouse_Positioning_Interface", "<html><head/><body><p>mm</p></body></html>", None))
        self.label_52.setText(_translate("Mouse_Positioning_Interface", "dx=", None))
        self.TxtRG_pxcalc.setText(_translate("Mouse_Positioning_Interface", "Pixel Spacing:", None))
        self.label_26.setText(_translate("Mouse_Positioning_Interface", "dy=", None))
        self.label_54.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.Group_Result.setTitle(_translate("Mouse_Positioning_Interface", "Result", None))
        self.label_60.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.label_59.setText(_translate("Mouse_Positioning_Interface", "mm", None))
        self.label_4.setText(_translate("Mouse_Positioning_Interface", "Calculated table position:", None))
        self.label_9.setText(_translate("Mouse_Positioning_Interface", "x_Table=", None))
        self.label_10.setText(_translate("Mouse_Positioning_Interface", "y_Table=", None))
        self.Button_LogFile.setText(_translate("Mouse_Positioning_Interface", "Print Logfile", None))
        self.Button_Exit.setText(_translate("Mouse_Positioning_Interface", "Exit", None))
        self.actionLoad_Radiography_scatter.setText(_translate("Mouse_Positioning_Interface", "Load Radiography (scatter)", None))

from matplotlibwidgetFile import matplotlibWidget
