# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Dokumente\Promotion\Projects\Protonenexperimente\Scripts\Positioning_GUI\V2.5\Backend\Target.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Target(object):
    def setupUi(self, Target):
        Target.setObjectName("Target")
        Target.resize(691, 517)
        self.centralwidget = QtWidgets.QWidget(Target)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 461))
        self.groupBox.setObjectName("groupBox")
        self.Display_XRay = matplotlibWidget(self.groupBox)
        self.Display_XRay.setGeometry(QtCore.QRect(100, 50, 400, 400))
        self.Display_XRay.setObjectName("Display_XRay")
        self.Button_Done = QtWidgets.QPushButton(self.groupBox)
        self.Button_Done.setGeometry(QtCore.QRect(540, 400, 111, 31))
        self.Button_Done.setObjectName("Button_Done")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 81, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 40, 371))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GreyValue_center = QtWidgets.QSlider(self.layoutWidget)
        self.GreyValue_center.setOrientation(QtCore.Qt.Vertical)
        self.GreyValue_center.setObjectName("GreyValue_center")
        self.horizontalLayout_2.addWidget(self.GreyValue_center)
        self.GreyValue_range = QtWidgets.QSlider(self.layoutWidget)
        self.GreyValue_range.setOrientation(QtCore.Qt.Vertical)
        self.GreyValue_range.setObjectName("GreyValue_range")
        self.horizontalLayout_2.addWidget(self.GreyValue_range)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Scrollbar_center = QtWidgets.QLabel(self.layoutWidget_2)
        self.Label_Scrollbar_center.setAutoFillBackground(True)
        self.Label_Scrollbar_center.setObjectName("Label_Scrollbar_center")
        self.horizontalLayout.addWidget(self.Label_Scrollbar_center)
        self.Label_Scrollbar_range = QtWidgets.QLabel(self.layoutWidget_2)
        self.Label_Scrollbar_range.setObjectName("Label_Scrollbar_range")
        self.horizontalLayout.addWidget(self.Label_Scrollbar_range)
        self.Button_setTarget = QtWidgets.QPushButton(self.groupBox)
        self.Button_setTarget.setGeometry(QtCore.QRect(540, 30, 111, 31))
        self.Button_setTarget.setObjectName("Button_setTarget")
        self.Slider_TargetX = QtWidgets.QSlider(self.groupBox)
        self.Slider_TargetX.setGeometry(QtCore.QRect(100, 20, 401, 19))
        self.Slider_TargetX.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_TargetX.setObjectName("Slider_TargetX")
        self.Slider_TargetY = QtWidgets.QSlider(self.groupBox)
        self.Slider_TargetY.setGeometry(QtCore.QRect(510, 50, 19, 391))
        self.Slider_TargetY.setOrientation(QtCore.Qt.Vertical)
        self.Slider_TargetY.setInvertedAppearance(True)
        self.Slider_TargetY.setObjectName("Slider_TargetY")
        self.Button_lockTarget = QtWidgets.QPushButton(self.groupBox)
        self.Button_lockTarget.setGeometry(QtCore.QRect(540, 130, 111, 31))
        self.Button_lockTarget.setObjectName("Button_lockTarget")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(542, 72, 111, 48))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.TxtTrgtX = QtWidgets.QLineEdit(self.widget)
        self.TxtTrgtX.setObjectName("TxtTrgtX")
        self.gridLayout.addWidget(self.TxtTrgtX, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.TxtTrgtY = QtWidgets.QLineEdit(self.widget)
        self.TxtTrgtY.setObjectName("TxtTrgtY")
        self.gridLayout.addWidget(self.TxtTrgtY, 1, 1, 1, 1)
        Target.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Target)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 21))
        self.menubar.setObjectName("menubar")
        Target.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Target)
        self.statusbar.setObjectName("statusbar")
        Target.setStatusBar(self.statusbar)

        self.retranslateUi(Target)
        QtCore.QMetaObject.connectSlotsByName(Target)

    def retranslateUi(self, Target):
        _translate = QtCore.QCoreApplication.translate
        Target.setWindowTitle(_translate("Target", "TargetDefinition"))
        self.groupBox.setTitle(_translate("Target", "Target"))
        self.Button_Done.setText(_translate("Target", "Done"))
        self.groupBox_2.setTitle(_translate("Target", "Gray Window"))
        self.Label_Scrollbar_center.setText(_translate("Target", "0"))
        self.Label_Scrollbar_range.setText(_translate("Target", "0"))
        self.Button_setTarget.setText(_translate("Target", "Set Target"))
        self.Button_lockTarget.setText(_translate("Target", "Lock"))
        self.label_5.setText(_translate("Target", "x="))
        self.label_6.setText(_translate("Target", "y="))

from matplotlibwidgetFile import matplotlibWidget
