# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Positioning_Assistant_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mouse_Positioning_Interface(object):
    def setupUi(self, Mouse_Positioning_Interface):
        Mouse_Positioning_Interface.setObjectName("Mouse_Positioning_Interface")
        Mouse_Positioning_Interface.setEnabled(True)
        Mouse_Positioning_Interface.resize(1708, 916)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mouse_Positioning_Interface.sizePolicy().hasHeightForWidth())
        Mouse_Positioning_Interface.setSizePolicy(sizePolicy)
        Mouse_Positioning_Interface.setMinimumSize(QtCore.QSize(1708, 916))
        Mouse_Positioning_Interface.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Mouse_Positioning_Interface.setAutoFillBackground(False)
        Mouse_Positioning_Interface.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Mouse_Positioning_Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.Logo = QtWidgets.QLabel(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/Imgs/Icons/Pic.jpg"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 300))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.LogBox = QtWidgets.QVBoxLayout()
        self.LogBox.setObjectName("LogBox")
        self.gridLayout_14.addLayout(self.LogBox, 0, 0, 1, 1)
        self.gridLayout_50.addWidget(self.splitter_4, 0, 1, 2, 1)
        self.GroupCoordinates = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupCoordinates.sizePolicy().hasHeightForWidth())
        self.GroupCoordinates.setSizePolicy(sizePolicy)
        self.GroupCoordinates.setMinimumSize(QtCore.QSize(0, 100))
        self.GroupCoordinates.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupCoordinates.setFont(font)
        self.GroupCoordinates.setObjectName("GroupCoordinates")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.GroupCoordinates)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SS_IsoCenter = QtWidgets.QFrame(self.GroupCoordinates)
        self.SS_IsoCenter.setMinimumSize(QtCore.QSize(0, 20))
        self.SS_IsoCenter.setAutoFillBackground(False)
        self.SS_IsoCenter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SS_IsoCenter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SS_IsoCenter.setObjectName("SS_IsoCenter")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.SS_IsoCenter)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.SS_IC_Label = QtWidgets.QLabel(self.SS_IsoCenter)
        self.SS_IC_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.SS_IC_Label.setObjectName("SS_IC_Label")
        self.gridLayout_43.addWidget(self.SS_IC_Label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SS_IsoCenter)
        self.label_7 = QtWidgets.QLabel(self.GroupCoordinates)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Arrows/Icons/move_right.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.SS_PlanImage = QtWidgets.QFrame(self.GroupCoordinates)
        self.SS_PlanImage.setMinimumSize(QtCore.QSize(0, 20))
        self.SS_PlanImage.setAutoFillBackground(False)
        self.SS_PlanImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SS_PlanImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SS_PlanImage.setObjectName("SS_PlanImage")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.SS_PlanImage)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.SS_Plan_Box_2 = QtWidgets.QLabel(self.SS_PlanImage)
        self.SS_Plan_Box_2.setAlignment(QtCore.Qt.AlignCenter)
        self.SS_Plan_Box_2.setObjectName("SS_Plan_Box_2")
        self.gridLayout_44.addWidget(self.SS_Plan_Box_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SS_PlanImage)
        self.label_8 = QtWidgets.QLabel(self.GroupCoordinates)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Arrows/Icons/move_right.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.SS_TreatImage = QtWidgets.QFrame(self.GroupCoordinates)
        self.SS_TreatImage.setMinimumSize(QtCore.QSize(0, 20))
        self.SS_TreatImage.setAutoFillBackground(False)
        self.SS_TreatImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SS_TreatImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SS_TreatImage.setObjectName("SS_TreatImage")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.SS_TreatImage)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.LabelCOM_4 = QtWidgets.QLabel(self.SS_TreatImage)
        self.LabelCOM_4.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCOM_4.setObjectName("LabelCOM_4")
        self.gridLayout_47.addWidget(self.LabelCOM_4, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SS_TreatImage)
        self.label_11 = QtWidgets.QLabel(self.GroupCoordinates)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Arrows/Icons/move_right.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.SS_RegApproved = QtWidgets.QFrame(self.GroupCoordinates)
        self.SS_RegApproved.setMinimumSize(QtCore.QSize(0, 20))
        self.SS_RegApproved.setAutoFillBackground(False)
        self.SS_RegApproved.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SS_RegApproved.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SS_RegApproved.setObjectName("SS_RegApproved")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.SS_RegApproved)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.LabelCOM_5 = QtWidgets.QLabel(self.SS_RegApproved)
        self.LabelCOM_5.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCOM_5.setObjectName("LabelCOM_5")
        self.gridLayout_49.addWidget(self.LabelCOM_5, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SS_RegApproved)
        self.label_12 = QtWidgets.QLabel(self.GroupCoordinates)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/Arrows/Icons/move_right.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.SS_StageSet = QtWidgets.QFrame(self.GroupCoordinates)
        self.SS_StageSet.setMinimumSize(QtCore.QSize(0, 20))
        self.SS_StageSet.setAutoFillBackground(False)
        self.SS_StageSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SS_StageSet.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SS_StageSet.setObjectName("SS_StageSet")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.SS_StageSet)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.LabelCOM_6 = QtWidgets.QLabel(self.SS_StageSet)
        self.LabelCOM_6.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCOM_6.setObjectName("LabelCOM_6")
        self.gridLayout_52.addWidget(self.LabelCOM_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SS_StageSet)
        self.label_16 = QtWidgets.QLabel(self.GroupCoordinates)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/Arrows/Icons/move_right.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.Button_create_report = QtWidgets.QPushButton(self.GroupCoordinates)
        self.Button_create_report.setMaximumSize(QtCore.QSize(16777215, 500))
        self.Button_create_report.setObjectName("Button_create_report")
        self.horizontalLayout.addWidget(self.Button_create_report)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_50.addWidget(self.GroupCoordinates, 1, 0, 1, 1)
        self.Registration = QtWidgets.QTabWidget(self.centralwidget)
        self.Registration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Registration.sizePolicy().hasHeightForWidth())
        self.Registration.setSizePolicy(sizePolicy)
        self.Registration.setObjectName("Registration")
        self.TabRadiography = QtWidgets.QWidget()
        self.TabRadiography.setObjectName("TabRadiography")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.TabRadiography)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Group_IsoCenter = QtWidgets.QGroupBox(self.TabRadiography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group_IsoCenter.sizePolicy().hasHeightForWidth())
        self.Group_IsoCenter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Group_IsoCenter.setFont(font)
        self.Group_IsoCenter.setObjectName("Group_IsoCenter")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Group_IsoCenter)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.Button_Radiograph_toggleIso = QtWidgets.QPushButton(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_Radiograph_toggleIso.setFont(font)
        self.Button_Radiograph_toggleIso.setObjectName("Button_Radiograph_toggleIso")
        self.gridLayout_5.addWidget(self.Button_Radiograph_toggleIso, 0, 2, 1, 2)
        self.Text_RG_Filename_IsoCenter = QtWidgets.QTextEdit(self.Group_IsoCenter)
        self.Text_RG_Filename_IsoCenter.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Text_RG_Filename_IsoCenter.setFont(font)
        self.Text_RG_Filename_IsoCenter.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_RG_Filename_IsoCenter.setObjectName("Text_RG_Filename_IsoCenter")
        self.gridLayout_5.addWidget(self.Text_RG_Filename_IsoCenter, 1, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 2, 1, 1)
        self.Button_RG_defineIsoCenter = QtWidgets.QPushButton(self.Group_IsoCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_RG_defineIsoCenter.setFont(font)
        self.Button_RG_defineIsoCenter.setObjectName("Button_RG_defineIsoCenter")
        self.gridLayout_5.addWidget(self.Button_RG_defineIsoCenter, 0, 0, 1, 2)
        self.SpotTxt_x = QtWidgets.QLineEdit(self.Group_IsoCenter)
        self.SpotTxt_x.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpotTxt_x.setFont(font)
        self.SpotTxt_x.setReadOnly(True)
        self.SpotTxt_x.setObjectName("SpotTxt_x")
        self.gridLayout_5.addWidget(self.SpotTxt_x, 2, 1, 1, 1)
        self.SpotTxt_y = QtWidgets.QLineEdit(self.Group_IsoCenter)
        self.SpotTxt_y.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpotTxt_y.setFont(font)
        self.SpotTxt_y.setReadOnly(True)
        self.SpotTxt_y.setObjectName("SpotTxt_y")
        self.gridLayout_5.addWidget(self.SpotTxt_y, 2, 3, 1, 1)
        self.gridLayout_15.addWidget(self.Group_IsoCenter, 1, 0, 1, 1)
        self.Display_Radiography = matplotlibWidget(self.TabRadiography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Radiography.sizePolicy().hasHeightForWidth())
        self.Display_Radiography.setSizePolicy(sizePolicy)
        self.Display_Radiography.setMinimumSize(QtCore.QSize(200, 200))
        self.Display_Radiography.setObjectName("Display_Radiography")
        self.gridLayout_15.addWidget(self.Display_Radiography, 0, 1, 1, 1)
        self.Display_Isocenter = matplotlibWidget(self.TabRadiography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Isocenter.sizePolicy().hasHeightForWidth())
        self.Display_Isocenter.setSizePolicy(sizePolicy)
        self.Display_Isocenter.setMinimumSize(QtCore.QSize(200, 200))
        self.Display_Isocenter.setObjectName("Display_Isocenter")
        self.gridLayout_15.addWidget(self.Display_Isocenter, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.TabRadiography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Button_RadiographyLM = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_RadiographyLM.sizePolicy().hasHeightForWidth())
        self.Button_RadiographyLM.setSizePolicy(sizePolicy)
        self.Button_RadiographyLM.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Button_RadiographyLM.setFont(font)
        self.Button_RadiographyLM.setAutoFillBackground(False)
        self.Button_RadiographyLM.setDefault(True)
        self.Button_RadiographyLM.setObjectName("Button_RadiographyLM")
        self.gridLayout_3.addWidget(self.Button_RadiographyLM, 0, 0, 1, 2)
        self.Button_toggleLandmarksRG = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_toggleLandmarksRG.sizePolicy().hasHeightForWidth())
        self.Button_toggleLandmarksRG.setSizePolicy(sizePolicy)
        self.Button_toggleLandmarksRG.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Button_toggleLandmarksRG.setFont(font)
        self.Button_toggleLandmarksRG.setAutoFillBackground(False)
        self.Button_toggleLandmarksRG.setDefault(True)
        self.Button_toggleLandmarksRG.setObjectName("Button_toggleLandmarksRG")
        self.gridLayout_3.addWidget(self.Button_toggleLandmarksRG, 0, 3, 1, 1)
        self.Text_RG_Filename_Landmark = QtWidgets.QTextEdit(self.groupBox_3)
        self.Text_RG_Filename_Landmark.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Text_RG_Filename_Landmark.setFont(font)
        self.Text_RG_Filename_Landmark.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_RG_Filename_Landmark.setObjectName("Text_RG_Filename_Landmark")
        self.gridLayout_3.addWidget(self.Text_RG_Filename_Landmark, 1, 0, 1, 4)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.TxtRGPinX = QtWidgets.QLineEdit(self.groupBox_3)
        self.TxtRGPinX.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TxtRGPinX.sizePolicy().hasHeightForWidth())
        self.TxtRGPinX.setSizePolicy(sizePolicy)
        self.TxtRGPinX.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtRGPinX.setFont(font)
        self.TxtRGPinX.setText("")
        self.TxtRGPinX.setObjectName("TxtRGPinX")
        self.gridLayout_3.addWidget(self.TxtRGPinX, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 2, 1, 1)
        self.TxtRGPinY = QtWidgets.QLineEdit(self.groupBox_3)
        self.TxtRGPinY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TxtRGPinY.sizePolicy().hasHeightForWidth())
        self.TxtRGPinY.setSizePolicy(sizePolicy)
        self.TxtRGPinY.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TxtRGPinY.setFont(font)
        self.TxtRGPinY.setText("")
        self.TxtRGPinY.setObjectName("TxtRGPinY")
        self.gridLayout_3.addWidget(self.TxtRGPinY, 2, 3, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_3, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem1, 0, 2, 1, 1)
        self.Registration.addTab(self.TabRadiography, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_20.sizePolicy().hasHeightForWidth())
        self.groupBox_20.setSizePolicy(sizePolicy)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Button_RunReg = QtWidgets.QPushButton(self.groupBox_20)
        self.Button_RunReg.setObjectName("Button_RunReg")
        self.gridLayout_10.addWidget(self.Button_RunReg, 2, 0, 1, 1)
        self.Slider_RegOverlay = QtWidgets.QSlider(self.groupBox_20)
        self.Slider_RegOverlay.setMaximum(100)
        self.Slider_RegOverlay.setSingleStep(0)
        self.Slider_RegOverlay.setProperty("value", 50)
        self.Slider_RegOverlay.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_RegOverlay.setObjectName("Slider_RegOverlay")
        self.gridLayout_10.addWidget(self.Slider_RegOverlay, 1, 0, 1, 2)
        self.Button_AccReg = QtWidgets.QPushButton(self.groupBox_20)
        self.Button_AccReg.setObjectName("Button_AccReg")
        self.gridLayout_10.addWidget(self.Button_AccReg, 2, 1, 1, 1)
        self.Display_Fusion = matplotlibWidget(self.groupBox_20)
        self.Display_Fusion.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Fusion.sizePolicy().hasHeightForWidth())
        self.Display_Fusion.setSizePolicy(sizePolicy)
        self.Display_Fusion.setMinimumSize(QtCore.QSize(300, 300))
        self.Display_Fusion.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.Display_Fusion.setObjectName("Display_Fusion")
        self.gridLayout_10.addWidget(self.Display_Fusion, 0, 0, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_20, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setMinimumSize(QtCore.QSize(250, 170))
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_default_moving = QtWidgets.QPushButton(self.groupBox_21)
        self.Button_default_moving.setObjectName("Button_default_moving")
        self.gridLayout.addWidget(self.Button_default_moving, 1, 0, 2, 2)
        self.CoordsTable = QtWidgets.QTableWidget(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CoordsTable.sizePolicy().hasHeightForWidth())
        self.CoordsTable.setSizePolicy(sizePolicy)
        self.CoordsTable.setMinimumSize(QtCore.QSize(0, 20))
        self.CoordsTable.setMaximumSize(QtCore.QSize(500, 150))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.CoordsTable.setFont(font)
        self.CoordsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.CoordsTable.setDragDropOverwriteMode(False)
        self.CoordsTable.setObjectName("CoordsTable")
        self.CoordsTable.setColumnCount(2)
        self.CoordsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CoordsTable.setItem(4, 1, item)
        self.CoordsTable.horizontalHeader().setDefaultSectionSize(60)
        self.CoordsTable.verticalHeader().setDefaultSectionSize(22)
        self.gridLayout.addWidget(self.CoordsTable, 0, 0, 1, 2)
        self.Button_default_fixed = QtWidgets.QPushButton(self.groupBox_21)
        self.Button_default_fixed.setObjectName("Button_default_fixed")
        self.gridLayout.addWidget(self.Button_default_fixed, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_21, 0, 0, 3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Slider_MarkerSize_Moving = QtWidgets.QSlider(self.groupBox_2)
        self.Slider_MarkerSize_Moving.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_MarkerSize_Moving.setObjectName("Slider_MarkerSize_Moving")
        self.gridLayout_6.addWidget(self.Slider_MarkerSize_Moving, 0, 1, 1, 1)
        self.Slider_MarkerSize_Fixed = QtWidgets.QSlider(self.groupBox_2)
        self.Slider_MarkerSize_Fixed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_MarkerSize_Fixed.setObjectName("Slider_MarkerSize_Fixed")
        self.gridLayout_6.addWidget(self.Slider_MarkerSize_Fixed, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_10.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAutoFillBackground(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TableTxt_y = QtWidgets.QLineEdit(self.groupBox_10)
        self.TableTxt_y.setEnabled(False)
        self.TableTxt_y.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TableTxt_y.setFont(font)
        self.TableTxt_y.setObjectName("TableTxt_y")
        self.gridLayout_2.addWidget(self.TableTxt_y, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.TableTxt_x = QtWidgets.QLineEdit(self.groupBox_10)
        self.TableTxt_x.setEnabled(False)
        self.TableTxt_x.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TableTxt_x.setFont(font)
        self.TableTxt_x.setObjectName("TableTxt_x")
        self.gridLayout_2.addWidget(self.TableTxt_x, 0, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.Group_Result = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group_Result.sizePolicy().hasHeightForWidth())
        self.Group_Result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Group_Result.setFont(font)
        self.Group_Result.setObjectName("Group_Result")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Group_Result)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.TableTxt_yCorr = QtWidgets.QLineEdit(self.Group_Result)
        self.TableTxt_yCorr.setEnabled(False)
        self.TableTxt_yCorr.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TableTxt_yCorr.setFont(font)
        self.TableTxt_yCorr.setObjectName("TableTxt_yCorr")
        self.gridLayout_8.addWidget(self.TableTxt_yCorr, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.TableTxt_xCorr = QtWidgets.QLineEdit(self.Group_Result)
        self.TableTxt_xCorr.setEnabled(False)
        self.TableTxt_xCorr.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TableTxt_xCorr.setFont(font)
        self.TableTxt_xCorr.setObjectName("TableTxt_xCorr")
        self.gridLayout_8.addWidget(self.TableTxt_xCorr, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_8.addWidget(self.label_59, 0, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Group_Result)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.Group_Result)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 4, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 5, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_22.setObjectName("groupBox_22")
        self.Label_Trafo_Params = QtWidgets.QLabel(self.groupBox_22)
        self.Label_Trafo_Params.setGeometry(QtCore.QRect(10, 42, 59, 16))
        self.Label_Trafo_Params.setObjectName("Label_Trafo_Params")
        self.label_15 = QtWidgets.QLabel(self.groupBox_22)
        self.label_15.setGeometry(QtCore.QRect(10, 23, 98, 16))
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.groupBox_22, 1, 2, 2, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_24.setObjectName("groupBox_24")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.groupBox_24)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.splitter_8 = QtWidgets.QSplitter(self.groupBox_24)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label_19 = QtWidgets.QLabel(self.splitter_7)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.splitter_7)
        self.label_20.setObjectName("label_20")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.Box_MotorOriginX = QtWidgets.QDoubleSpinBox(self.splitter_5)
        self.Box_MotorOriginX.setEnabled(True)
        self.Box_MotorOriginX.setDecimals(3)
        self.Box_MotorOriginX.setMaximum(1000.0)
        self.Box_MotorOriginX.setObjectName("Box_MotorOriginX")
        self.Box_MotorOriginY = QtWidgets.QDoubleSpinBox(self.splitter_5)
        self.Box_MotorOriginY.setDecimals(3)
        self.Box_MotorOriginY.setMaximum(1000.0)
        self.Box_MotorOriginY.setObjectName("Box_MotorOriginY")
        self.Btn_setMotor_Origin = QtWidgets.QPushButton(self.splitter_6)
        self.Btn_setMotor_Origin.setObjectName("Btn_setMotor_Origin")
        self.gridLayout_51.addWidget(self.splitter_8, 1, 0, 1, 1)
        self.Btn_getCurrentMotor = QtWidgets.QPushButton(self.groupBox_24)
        self.Btn_getCurrentMotor.setObjectName("Btn_getCurrentMotor")
        self.gridLayout_51.addWidget(self.Btn_getCurrentMotor, 0, 0, 1, 1)
        self.Btn_Reg_calcTable = QtWidgets.QPushButton(self.groupBox_24)
        self.Btn_Reg_calcTable.setObjectName("Btn_Reg_calcTable")
        self.gridLayout_51.addWidget(self.Btn_Reg_calcTable, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem3, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_24, 0, 3, 3, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        self.groupBox_23.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_23.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.table_TrgCoords = QtWidgets.QTableWidget(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_TrgCoords.sizePolicy().hasHeightForWidth())
        self.table_TrgCoords.setSizePolicy(sizePolicy)
        self.table_TrgCoords.setMinimumSize(QtCore.QSize(0, 0))
        self.table_TrgCoords.setMaximumSize(QtCore.QSize(200, 16777215))
        self.table_TrgCoords.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_TrgCoords.setObjectName("table_TrgCoords")
        self.table_TrgCoords.setColumnCount(2)
        self.table_TrgCoords.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TrgCoords.setItem(1, 0, item)
        self.table_TrgCoords.horizontalHeader().setDefaultSectionSize(58)
        self.table_TrgCoords.horizontalHeader().setMinimumSectionSize(40)
        self.table_TrgCoords.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_12.addWidget(self.table_TrgCoords, 0, 0, 1, 2)
        self.Button_flip_layers = QtWidgets.QPushButton(self.groupBox_23)
        self.Button_flip_layers.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Button_flip_layers.setObjectName("Button_flip_layers")
        self.gridLayout_12.addWidget(self.Button_flip_layers, 1, 0, 1, 1)
        self.Button_show_Atlas = QtWidgets.QPushButton(self.groupBox_23)
        self.Button_show_Atlas.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Button_show_Atlas.setObjectName("Button_show_Atlas")
        self.gridLayout_12.addWidget(self.Button_show_Atlas, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_23, 0, 1, 3, 1)
        self.gridLayout_11.addWidget(self.frame_4, 1, 0, 1, 3)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Graybar_Moving = matplotlibWidget(self.groupBox_18)
        self.Graybar_Moving.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graybar_Moving.sizePolicy().hasHeightForWidth())
        self.Graybar_Moving.setSizePolicy(sizePolicy)
        self.Graybar_Moving.setMinimumSize(QtCore.QSize(0, 80))
        self.Graybar_Moving.setMaximumSize(QtCore.QSize(1000000, 100))
        self.Graybar_Moving.setObjectName("Graybar_Moving")
        self.verticalLayout.addWidget(self.Graybar_Moving)
        self.Display_Moving = matplotlibWidget(self.groupBox_18)
        self.Display_Moving.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Moving.sizePolicy().hasHeightForWidth())
        self.Display_Moving.setSizePolicy(sizePolicy)
        self.Display_Moving.setMinimumSize(QtCore.QSize(300, 100))
        self.Display_Moving.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.Display_Moving.setObjectName("Display_Moving")
        self.verticalLayout.addWidget(self.Display_Moving)
        self.Button_load_moving = QtWidgets.QPushButton(self.groupBox_18)
        self.Button_load_moving.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Button_load_moving.setObjectName("Button_load_moving")
        self.verticalLayout.addWidget(self.Button_load_moving)
        self.Label_Moving = QtWidgets.QLabel(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Moving.sizePolicy().hasHeightForWidth())
        self.Label_Moving.setSizePolicy(sizePolicy)
        self.Label_Moving.setMinimumSize(QtCore.QSize(0, 20))
        self.Label_Moving.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Label_Moving.setText("")
        self.Label_Moving.setObjectName("Label_Moving")
        self.verticalLayout.addWidget(self.Label_Moving)
        self.gridLayout_11.addWidget(self.groupBox_18, 0, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_19.sizePolicy().hasHeightForWidth())
        self.groupBox_19.setSizePolicy(sizePolicy)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.Display_Fixed = matplotlibWidget(self.groupBox_19)
        self.Display_Fixed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Fixed.sizePolicy().hasHeightForWidth())
        self.Display_Fixed.setSizePolicy(sizePolicy)
        self.Display_Fixed.setMinimumSize(QtCore.QSize(300, 300))
        self.Display_Fixed.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.Display_Fixed.setObjectName("Display_Fixed")
        self.gridLayout_45.addWidget(self.Display_Fixed, 1, 0, 1, 1)
        self.Button_load_fixed = QtWidgets.QPushButton(self.groupBox_19)
        self.Button_load_fixed.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Button_load_fixed.setObjectName("Button_load_fixed")
        self.gridLayout_45.addWidget(self.Button_load_fixed, 2, 0, 1, 1)
        self.Label_Fixed = QtWidgets.QLabel(self.groupBox_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_Fixed.sizePolicy().hasHeightForWidth())
        self.Label_Fixed.setSizePolicy(sizePolicy)
        self.Label_Fixed.setMinimumSize(QtCore.QSize(0, 0))
        self.Label_Fixed.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Label_Fixed.setText("")
        self.Label_Fixed.setObjectName("Label_Fixed")
        self.gridLayout_45.addWidget(self.Label_Fixed, 3, 0, 1, 1)
        self.Graybar_Fixed = matplotlibWidget(self.groupBox_19)
        self.Graybar_Fixed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graybar_Fixed.sizePolicy().hasHeightForWidth())
        self.Graybar_Fixed.setSizePolicy(sizePolicy)
        self.Graybar_Fixed.setMinimumSize(QtCore.QSize(0, 80))
        self.Graybar_Fixed.setMaximumSize(QtCore.QSize(1000000, 100))
        self.Graybar_Fixed.setObjectName("Graybar_Fixed")
        self.gridLayout_45.addWidget(self.Graybar_Fixed, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_19, 0, 1, 1, 1)
        self.Registration.addTab(self.tab, "")
        self.TabMotor = QtWidgets.QWidget()
        self.TabMotor.setObjectName("TabMotor")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.TabMotor)
        self.gridLayout_42.setObjectName("gridLayout_42")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_42.addItem(spacerItem5, 0, 3, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.TabMotor)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.BoxTableCOM = QtWidgets.QFrame(self.groupBox_6)
        self.BoxTableCOM.setMinimumSize(QtCore.QSize(0, 20))
        self.BoxTableCOM.setAutoFillBackground(False)
        self.BoxTableCOM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoxTableCOM.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BoxTableCOM.setObjectName("BoxTableCOM")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.BoxTableCOM)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.LabelCOM = QtWidgets.QLabel(self.BoxTableCOM)
        self.LabelCOM.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCOM.setObjectName("LabelCOM")
        self.gridLayout_39.addWidget(self.LabelCOM, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.BoxTableCOM, 7, 0, 1, 1)
        self.BoxTableLimits = QtWidgets.QFrame(self.groupBox_6)
        self.BoxTableLimits.setMinimumSize(QtCore.QSize(0, 20))
        self.BoxTableLimits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoxTableLimits.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BoxTableLimits.setObjectName("BoxTableLimits")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.BoxTableLimits)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.LabelREF = QtWidgets.QLabel(self.BoxTableLimits)
        self.LabelREF.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelREF.setObjectName("LabelREF")
        self.gridLayout_41.addWidget(self.LabelREF, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.BoxTableLimits, 9, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 4, 0, 1, 1)
        self.Label_COMPort = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_COMPort.setFont(font)
        self.Label_COMPort.setObjectName("Label_COMPort")
        self.gridLayout_7.addWidget(self.Label_COMPort, 0, 0, 1, 1)
        self.QComboBox_ListOfPorts = QtWidgets.QComboBox(self.groupBox_6)
        self.QComboBox_ListOfPorts.setEnabled(True)
        self.QComboBox_ListOfPorts.setObjectName("QComboBox_ListOfPorts")
        self.gridLayout_7.addWidget(self.QComboBox_ListOfPorts, 1, 0, 1, 1)
        self.Button_MotorInit = QtWidgets.QPushButton(self.groupBox_6)
        self.Button_MotorInit.setObjectName("Button_MotorInit")
        self.gridLayout_7.addWidget(self.Button_MotorInit, 2, 0, 1, 1)
        self.Button_MotorDisconnect = QtWidgets.QPushButton(self.groupBox_6)
        self.Button_MotorDisconnect.setObjectName("Button_MotorDisconnect")
        self.gridLayout_7.addWidget(self.Button_MotorDisconnect, 3, 0, 1, 1)
        self.CBoxABSREL = QtWidgets.QComboBox(self.groupBox_6)
        self.CBoxABSREL.setMinimumSize(QtCore.QSize(100, 0))
        self.CBoxABSREL.setCurrentText("")
        self.CBoxABSREL.setObjectName("CBoxABSREL")
        self.gridLayout_7.addWidget(self.CBoxABSREL, 5, 0, 1, 1)
        self.BoxTableInit = QtWidgets.QFrame(self.groupBox_6)
        self.BoxTableInit.setMinimumSize(QtCore.QSize(0, 20))
        self.BoxTableInit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoxTableInit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BoxTableInit.setObjectName("BoxTableInit")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.BoxTableInit)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.LabelINIT = QtWidgets.QLabel(self.BoxTableInit)
        self.LabelINIT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelINIT.setObjectName("LabelINIT")
        self.gridLayout_40.addWidget(self.LabelINIT, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.BoxTableInit, 10, 0, 1, 1)
        self.gridLayout_42.addWidget(self.groupBox_6, 0, 0, 2, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.TabMotor)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.TablePosX = QtWidgets.QLineEdit(self.groupBox_4)
        self.TablePosX.setEnabled(False)
        self.TablePosX.setObjectName("TablePosX")
        self.horizontalLayout_4.addWidget(self.TablePosX)
        self.label_66 = QtWidgets.QLabel(self.groupBox_4)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_4.addWidget(self.label_66)
        self.gridLayout_25.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_64 = QtWidgets.QLabel(self.groupBox_4)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_3.addWidget(self.label_64)
        self.TablePosY = QtWidgets.QLineEdit(self.groupBox_4)
        self.TablePosY.setEnabled(False)
        self.TablePosY.setObjectName("TablePosY")
        self.horizontalLayout_3.addWidget(self.TablePosY)
        self.label_65 = QtWidgets.QLabel(self.groupBox_4)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_3.addWidget(self.label_65)
        self.gridLayout_25.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem7, 2, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.Button_MoveTable = QtWidgets.QPushButton(self.groupBox_13)
        self.Button_MoveTable.setObjectName("Button_MoveTable")
        self.gridLayout_34.addWidget(self.Button_MoveTable, 2, 0, 1, 1)
        self.Button_StopTable = QtWidgets.QPushButton(self.groupBox_13)
        self.Button_StopTable.setObjectName("Button_StopTable")
        self.gridLayout_34.addWidget(self.Button_StopTable, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_69 = QtWidgets.QLabel(self.groupBox_13)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_7.addWidget(self.label_69)
        self.SpinBoxTabley = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.SpinBoxTabley.setDecimals(3)
        self.SpinBoxTabley.setMinimum(-70000.0)
        self.SpinBoxTabley.setMaximum(70000.0)
        self.SpinBoxTabley.setSingleStep(0.1)
        self.SpinBoxTabley.setObjectName("SpinBoxTabley")
        self.horizontalLayout_7.addWidget(self.SpinBoxTabley)
        self.label_70 = QtWidgets.QLabel(self.groupBox_13)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_7.addWidget(self.label_70)
        self.gridLayout_34.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem8, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_67 = QtWidgets.QLabel(self.groupBox_13)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_6.addWidget(self.label_67)
        self.SpinBoxTablex = QtWidgets.QDoubleSpinBox(self.groupBox_13)
        self.SpinBoxTablex.setDecimals(3)
        self.SpinBoxTablex.setMinimum(-70000.0)
        self.SpinBoxTablex.setMaximum(70000.0)
        self.SpinBoxTablex.setSingleStep(0.1)
        self.SpinBoxTablex.setObjectName("SpinBoxTablex")
        self.horizontalLayout_6.addWidget(self.SpinBoxTablex)
        self.label_68 = QtWidgets.QLabel(self.groupBox_13)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_6.addWidget(self.label_68)
        self.gridLayout_34.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.ButtonCopyCoordinates = QtWidgets.QPushButton(self.groupBox_13)
        self.ButtonCopyCoordinates.setObjectName("ButtonCopyCoordinates")
        self.gridLayout_34.addWidget(self.ButtonCopyCoordinates, 4, 0, 1, 1)
        self.gridLayout_42.addWidget(self.splitter_3, 0, 1, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(108, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_42.addItem(spacerItem9, 1, 2, 1, 1)
        self.Registration.addTab(self.TabMotor, "")
        self.gridLayout_50.addWidget(self.Registration, 0, 0, 1, 1)
        Mouse_Positioning_Interface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Mouse_Positioning_Interface)
        self.statusbar.setObjectName("statusbar")
        Mouse_Positioning_Interface.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Mouse_Positioning_Interface)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1708, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuActions = QtWidgets.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuLog_Level = QtWidgets.QMenu(self.menuOptions)
        self.menuLog_Level.setObjectName("menuLog_Level")
        self.menuUtils = QtWidgets.QMenu(self.menuBar)
        self.menuUtils.setObjectName("menuUtils")
        Mouse_Positioning_Interface.setMenuBar(self.menuBar)
        self.actionLoad_Radiography_scatter = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.actionLoad_Radiography_scatter.setObjectName("actionLoad_Radiography_scatter")
        self.action_SaveLogfile = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_SaveLogfile.setObjectName("action_SaveLogfile")
        self.action_Exit = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_Exit.setObjectName("action_Exit")
        self.actionRestore_Old_Session = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.actionRestore_Old_Session.setObjectName("actionRestore_Old_Session")
        self.action_LogLevel_Info = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_LogLevel_Info.setCheckable(True)
        self.action_LogLevel_Info.setObjectName("action_LogLevel_Info")
        self.action_LogLevel_Debug = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_LogLevel_Debug.setCheckable(True)
        self.action_LogLevel_Debug.setObjectName("action_LogLevel_Debug")
        self.action_Log_Serial_Com = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_Log_Serial_Com.setCheckable(True)
        self.action_Log_Serial_Com.setObjectName("action_Log_Serial_Com")
        self.actionSet_Logfile_Directory = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.actionSet_Logfile_Directory.setObjectName("actionSet_Logfile_Directory")
        self.action_scan_COM_ports = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_scan_COM_ports.setObjectName("action_scan_COM_ports")
        self.actionN2V_for_RG = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.actionN2V_for_RG.setObjectName("actionN2V_for_RG")
        self.action_set_beam_diameter = QtWidgets.QAction(Mouse_Positioning_Interface)
        self.action_set_beam_diameter.setObjectName("action_set_beam_diameter")
        self.menuActions.addAction(self.action_Exit)
        self.menuLog_Level.addAction(self.action_LogLevel_Info)
        self.menuLog_Level.addAction(self.action_LogLevel_Debug)
        self.menuOptions.addAction(self.menuLog_Level.menuAction())
        self.menuOptions.addAction(self.action_Log_Serial_Com)
        self.menuOptions.addAction(self.actionSet_Logfile_Directory)
        self.menuUtils.addAction(self.action_scan_COM_ports)
        self.menuUtils.addAction(self.actionN2V_for_RG)
        self.menuUtils.addAction(self.action_set_beam_diameter)
        self.menuBar.addAction(self.menuActions.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuUtils.menuAction())

        self.retranslateUi(Mouse_Positioning_Interface)
        self.Registration.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mouse_Positioning_Interface)

    def retranslateUi(self, Mouse_Positioning_Interface):
        _translate = QtCore.QCoreApplication.translate
        Mouse_Positioning_Interface.setWindowTitle(_translate("Mouse_Positioning_Interface", "Mouse Positioning Interface"))
        self.groupBox.setTitle(_translate("Mouse_Positioning_Interface", "Log"))
        self.GroupCoordinates.setTitle(_translate("Mouse_Positioning_Interface", "Workflow"))
        self.SS_IC_Label.setText(_translate("Mouse_Positioning_Interface", "IsoCenter"))
        self.SS_Plan_Box_2.setText(_translate("Mouse_Positioning_Interface", "Plan\n"
"Image"))
        self.LabelCOM_4.setText(_translate("Mouse_Positioning_Interface", "Treatment\n"
"Image"))
        self.LabelCOM_5.setText(_translate("Mouse_Positioning_Interface", "Registration\n"
"approved"))
        self.LabelCOM_6.setText(_translate("Mouse_Positioning_Interface", "Motor stage\n"
"set"))
        self.Button_create_report.setText(_translate("Mouse_Positioning_Interface", "Report"))
        self.Group_IsoCenter.setTitle(_translate("Mouse_Positioning_Interface", "IsoCenter"))
        self.label_5.setText(_translate("Mouse_Positioning_Interface", "x<sub>Iso</sub>="))
        self.Button_Radiograph_toggleIso.setText(_translate("Mouse_Positioning_Interface", "Toggle"))
        self.label_6.setText(_translate("Mouse_Positioning_Interface", "y<sub>Iso</sub>="))
        self.Button_RG_defineIsoCenter.setText(_translate("Mouse_Positioning_Interface", "Define"))
        self.groupBox_3.setTitle(_translate("Mouse_Positioning_Interface", "Landmarks"))
        self.Button_RadiographyLM.setText(_translate("Mouse_Positioning_Interface", "Set Landmarks"))
        self.Button_toggleLandmarksRG.setText(_translate("Mouse_Positioning_Interface", "Toggle Landmarks"))
        self.label_24.setText(_translate("Mouse_Positioning_Interface", "x<sub>Pin</sub>="))
        self.label_23.setText(_translate("Mouse_Positioning_Interface", "y<sub>Pin</sub>="))
        self.Registration.setTabText(self.Registration.indexOf(self.TabRadiography), _translate("Mouse_Positioning_Interface", "Radiography"))
        self.groupBox_20.setTitle(_translate("Mouse_Positioning_Interface", "Overlay"))
        self.Button_RunReg.setText(_translate("Mouse_Positioning_Interface", "Run Registration"))
        self.Button_AccReg.setText(_translate("Mouse_Positioning_Interface", "Accept Registration"))
        self.groupBox_21.setTitle(_translate("Mouse_Positioning_Interface", "Default landmark positions"))
        self.Button_default_moving.setText(_translate("Mouse_Positioning_Interface", "Set default positions (moving)"))
        item = self.CoordsTable.verticalHeaderItem(0)
        item.setText(_translate("Mouse_Positioning_Interface", "Marker 1"))
        item = self.CoordsTable.verticalHeaderItem(1)
        item.setText(_translate("Mouse_Positioning_Interface", "Marker 2"))
        item = self.CoordsTable.verticalHeaderItem(2)
        item.setText(_translate("Mouse_Positioning_Interface", "Marker 3"))
        item = self.CoordsTable.verticalHeaderItem(3)
        item.setText(_translate("Mouse_Positioning_Interface", "Marker 4"))
        item = self.CoordsTable.verticalHeaderItem(4)
        item.setText(_translate("Mouse_Positioning_Interface", "Marker 5"))
        item = self.CoordsTable.horizontalHeaderItem(0)
        item.setText(_translate("Mouse_Positioning_Interface", "Moving"))
        item = self.CoordsTable.horizontalHeaderItem(1)
        item.setText(_translate("Mouse_Positioning_Interface", "Fixed"))
        __sortingEnabled = self.CoordsTable.isSortingEnabled()
        self.CoordsTable.setSortingEnabled(False)
        item = self.CoordsTable.item(0, 0)
        item.setText(_translate("Mouse_Positioning_Interface", "655, 534"))
        item = self.CoordsTable.item(0, 1)
        item.setText(_translate("Mouse_Positioning_Interface", "655, 534"))
        item = self.CoordsTable.item(1, 0)
        item.setText(_translate("Mouse_Positioning_Interface", "592, 520"))
        item = self.CoordsTable.item(1, 1)
        item.setText(_translate("Mouse_Positioning_Interface", "592, 520"))
        item = self.CoordsTable.item(2, 0)
        item.setText(_translate("Mouse_Positioning_Interface", "494, 540"))
        item = self.CoordsTable.item(2, 1)
        item.setText(_translate("Mouse_Positioning_Interface", "494, 540"))
        item = self.CoordsTable.item(3, 0)
        item.setText(_translate("Mouse_Positioning_Interface", "602, 586"))
        item = self.CoordsTable.item(3, 1)
        item.setText(_translate("Mouse_Positioning_Interface", "602, 586"))
        item = self.CoordsTable.item(4, 0)
        item.setText(_translate("Mouse_Positioning_Interface", "703, 565"))
        item = self.CoordsTable.item(4, 1)
        item.setText(_translate("Mouse_Positioning_Interface", "703, 565"))
        self.CoordsTable.setSortingEnabled(__sortingEnabled)
        self.Button_default_fixed.setText(_translate("Mouse_Positioning_Interface", "Set default positions (fixed)"))
        self.groupBox_2.setTitle(_translate("Mouse_Positioning_Interface", "Marker Control"))
        self.label.setText(_translate("Mouse_Positioning_Interface", "Plan"))
        self.label_3.setText(_translate("Mouse_Positioning_Interface", "Treatment"))
        self.groupBox_10.setTitle(_translate("Mouse_Positioning_Interface", "Motor stage origin"))
        self.label_13.setText(_translate("Mouse_Positioning_Interface", "x<sub>Table</sub>="))
        self.label_57.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.label_14.setText(_translate("Mouse_Positioning_Interface", "y<sub>Table</sub>="))
        self.label_58.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.Group_Result.setTitle(_translate("Mouse_Positioning_Interface", "Calculated table position:"))
        self.label_9.setText(_translate("Mouse_Positioning_Interface", "x<sub>Table</sub>="))
        self.label_59.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.label_60.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.label_10.setText(_translate("Mouse_Positioning_Interface", "y<sub>Table<sub>="))
        self.groupBox_22.setTitle(_translate("Mouse_Positioning_Interface", "Transformation Parameters"))
        self.Label_Trafo_Params.setText(_translate("Mouse_Positioning_Interface", "Parameters:"))
        self.label_15.setText(_translate("Mouse_Positioning_Interface", "Transform: Similarity"))
        self.groupBox_24.setTitle(_translate("Mouse_Positioning_Interface", "Motor Coordinates"))
        self.label_19.setText(_translate("Mouse_Positioning_Interface", "hor"))
        self.label_20.setText(_translate("Mouse_Positioning_Interface", "ver"))
        self.Btn_setMotor_Origin.setText(_translate("Mouse_Positioning_Interface", "Set as Motor Origin"))
        self.Btn_getCurrentMotor.setText(_translate("Mouse_Positioning_Interface", "Get current motor coordinates"))
        self.Btn_Reg_calcTable.setText(_translate("Mouse_Positioning_Interface", "Calculate target table position"))
        self.groupBox_23.setTitle(_translate("Mouse_Positioning_Interface", "Target Coordinates"))
        item = self.table_TrgCoords.verticalHeaderItem(0)
        item.setText(_translate("Mouse_Positioning_Interface", "Raw"))
        item = self.table_TrgCoords.verticalHeaderItem(1)
        item.setText(_translate("Mouse_Positioning_Interface", "Transformed"))
        item = self.table_TrgCoords.horizontalHeaderItem(0)
        item.setText(_translate("Mouse_Positioning_Interface", "x, y"))
        item = self.table_TrgCoords.horizontalHeaderItem(1)
        item.setText(_translate("Mouse_Positioning_Interface", "Get"))
        __sortingEnabled = self.table_TrgCoords.isSortingEnabled()
        self.table_TrgCoords.setSortingEnabled(False)
        self.table_TrgCoords.setSortingEnabled(__sortingEnabled)
        self.Button_flip_layers.setText(_translate("Mouse_Positioning_Interface", "Flip Image"))
        self.Button_show_Atlas.setText(_translate("Mouse_Positioning_Interface", "Show Atlas"))
        self.groupBox_18.setTitle(_translate("Mouse_Positioning_Interface", "Planing image"))
        self.Button_load_moving.setText(_translate("Mouse_Positioning_Interface", "Load Image"))
        self.groupBox_19.setTitle(_translate("Mouse_Positioning_Interface", "Treatment Image"))
        self.Button_load_fixed.setText(_translate("Mouse_Positioning_Interface", "Load Image"))
        self.Registration.setTabText(self.Registration.indexOf(self.tab), _translate("Mouse_Positioning_Interface", "Active Positioning"))
        self.groupBox_6.setTitle(_translate("Mouse_Positioning_Interface", "Settings"))
        self.LabelCOM.setText(_translate("Mouse_Positioning_Interface", "Disconnected"))
        self.LabelREF.setText(_translate("Mouse_Positioning_Interface", "Not Calibrated"))
        self.label_2.setText(_translate("Mouse_Positioning_Interface", "Mode"))
        self.Label_COMPort.setText(_translate("Mouse_Positioning_Interface", "COM port"))
        self.Button_MotorInit.setText(_translate("Mouse_Positioning_Interface", "Connect"))
        self.Button_MotorDisconnect.setText(_translate("Mouse_Positioning_Interface", "Disconnect"))
        self.LabelINIT.setText(_translate("Mouse_Positioning_Interface", "Not ready"))
        self.groupBox_4.setTitle(_translate("Mouse_Positioning_Interface", "Current coordinates"))
        self.label_4.setText(_translate("Mouse_Positioning_Interface", "x = "))
        self.TablePosX.setText(_translate("Mouse_Positioning_Interface", "0"))
        self.label_66.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.label_64.setText(_translate("Mouse_Positioning_Interface", "y = "))
        self.TablePosY.setText(_translate("Mouse_Positioning_Interface", "0"))
        self.label_65.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.groupBox_13.setTitle(_translate("Mouse_Positioning_Interface", "Table movement"))
        self.Button_MoveTable.setText(_translate("Mouse_Positioning_Interface", "Move"))
        self.Button_StopTable.setText(_translate("Mouse_Positioning_Interface", "Stop"))
        self.label_69.setText(_translate("Mouse_Positioning_Interface", "y = "))
        self.label_70.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.label_67.setText(_translate("Mouse_Positioning_Interface", "x = "))
        self.label_68.setText(_translate("Mouse_Positioning_Interface", "mm"))
        self.ButtonCopyCoordinates.setText(_translate("Mouse_Positioning_Interface", "Copy Coordinates"))
        self.Registration.setTabText(self.Registration.indexOf(self.TabMotor), _translate("Mouse_Positioning_Interface", "Motor Control"))
        self.menuActions.setTitle(_translate("Mouse_Positioning_Interface", "File"))
        self.menuOptions.setTitle(_translate("Mouse_Positioning_Interface", "Logging"))
        self.menuLog_Level.setTitle(_translate("Mouse_Positioning_Interface", "Log Level"))
        self.menuUtils.setTitle(_translate("Mouse_Positioning_Interface", "Utils"))
        self.actionLoad_Radiography_scatter.setText(_translate("Mouse_Positioning_Interface", "Load Radiography (scatter)"))
        self.action_SaveLogfile.setText(_translate("Mouse_Positioning_Interface", "Save Logfile"))
        self.action_Exit.setText(_translate("Mouse_Positioning_Interface", "Exit"))
        self.actionRestore_Old_Session.setText(_translate("Mouse_Positioning_Interface", "Load Logfile"))
        self.action_LogLevel_Info.setText(_translate("Mouse_Positioning_Interface", "Info"))
        self.action_LogLevel_Debug.setText(_translate("Mouse_Positioning_Interface", "Debug"))
        self.action_Log_Serial_Com.setText(_translate("Mouse_Positioning_Interface", "Log Serial Com"))
        self.actionSet_Logfile_Directory.setText(_translate("Mouse_Positioning_Interface", "Set Logfile Directory"))
        self.action_scan_COM_ports.setText(_translate("Mouse_Positioning_Interface", "Rescan COM ports"))
        self.actionN2V_for_RG.setText(_translate("Mouse_Positioning_Interface", "Noise2Void for Radiography"))
        self.action_set_beam_diameter.setText(_translate("Mouse_Positioning_Interface", "Set Beam Diameter"))

from matplotlibwidgetFile import matplotlibWidget
import ressources_rc
