# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IsoCenter.ui'
#
# Created: Fri Apr 20 17:05:20 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IsoCenter(object):
    def setupUi(self, IsoCenter):
        IsoCenter.setObjectName(_fromUtf8("IsoCenter"))
        IsoCenter.resize(861, 609)
        self.centralwidget = QtGui.QWidget(IsoCenter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 791, 521))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Display_IsoCenter = matplotlibWidget(self.groupBox)
        self.Display_IsoCenter.setGeometry(QtCore.QRect(30, 30, 400, 400))
        self.Display_IsoCenter.setObjectName(_fromUtf8("Display_IsoCenter"))
        self.Display_yProfile = matplotlibWidget(self.groupBox)
        self.Display_yProfile.setGeometry(QtCore.QRect(440, 30, 60, 400))
        self.Display_yProfile.setObjectName(_fromUtf8("Display_yProfile"))
        self.Display_xProfile = matplotlibWidget(self.groupBox)
        self.Display_xProfile.setGeometry(QtCore.QRect(30, 440, 400, 60))
        self.Display_xProfile.setObjectName(_fromUtf8("Display_xProfile"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 10, 401, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalSlider = QtGui.QSlider(self.groupBox)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 30, 19, 401))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(True)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 260, 261, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Button_detectIsoCenter = QtGui.QPushButton(self.groupBox_2)
        self.Button_detectIsoCenter.setGeometry(QtCore.QRect(10, 20, 110, 31))
        self.Button_detectIsoCenter.setAutoFillBackground(False)
        self.Button_detectIsoCenter.setDefault(True)
        self.Button_detectIsoCenter.setObjectName(_fromUtf8("Button_detectIsoCenter"))
        self.Button_SetIsoCenter = QtGui.QPushButton(self.groupBox_2)
        self.Button_SetIsoCenter.setGeometry(QtCore.QRect(130, 20, 110, 31))
        self.Button_SetIsoCenter.setAutoFillBackground(False)
        self.Button_SetIsoCenter.setDefault(True)
        self.Button_SetIsoCenter.setObjectName(_fromUtf8("Button_SetIsoCenter"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 60, 221, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.SpotTxt_x = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.SpotTxt_x.setSingleStep(0.1)
        self.SpotTxt_x.setObjectName(_fromUtf8("SpotTxt_x"))
        self.horizontalLayout_2.addWidget(self.SpotTxt_x)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.SpotTxt_y = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.SpotTxt_y.setSingleStep(0.1)
        self.SpotTxt_y.setObjectName(_fromUtf8("SpotTxt_y"))
        self.horizontalLayout_2.addWidget(self.SpotTxt_y)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 20, 261, 101))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Button_LoadSpot = QtGui.QPushButton(self.groupBox_3)
        self.Button_LoadSpot.setEnabled(True)
        self.Button_LoadSpot.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.Button_LoadSpot.setDefault(True)
        self.Button_LoadSpot.setFlat(False)
        self.Button_LoadSpot.setObjectName(_fromUtf8("Button_LoadSpot"))
        self.Text_Filename = QtGui.QTextEdit(self.groupBox_3)
        self.Text_Filename.setEnabled(True)
        self.Text_Filename.setGeometry(QtCore.QRect(10, 60, 241, 31))
        self.Text_Filename.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_Filename.setObjectName(_fromUtf8("Text_Filename"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 130, 261, 121))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.Button_GetField = QtGui.QPushButton(self.groupBox_4)
        self.Button_GetField.setGeometry(QtCore.QRect(10, 20, 110, 31))
        self.Button_GetField.setAutoFillBackground(False)
        self.Button_GetField.setDefault(True)
        self.Button_GetField.setObjectName(_fromUtf8("Button_GetField"))
        self.Button_SetFieldLimits = QtGui.QPushButton(self.groupBox_4)
        self.Button_SetFieldLimits.setGeometry(QtCore.QRect(130, 20, 110, 31))
        self.Button_SetFieldLimits.setObjectName(_fromUtf8("Button_SetFieldLimits"))
        self.splitter = QtGui.QSplitter(self.groupBox_4)
        self.splitter.setGeometry(QtCore.QRect(10, 60, 231, 48))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.x_Left = QtGui.QLineEdit(self.layoutWidget1)
        self.x_Left.setObjectName(_fromUtf8("x_Left"))
        self.horizontalLayout.addWidget(self.x_Left)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.x_Right = QtGui.QLineEdit(self.layoutWidget1)
        self.x_Right.setObjectName(_fromUtf8("x_Right"))
        self.horizontalLayout.addWidget(self.x_Right)
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.y_bottom = QtGui.QLineEdit(self.layoutWidget_3)
        self.y_bottom.setObjectName(_fromUtf8("y_bottom"))
        self.horizontalLayout_10.addWidget(self.y_bottom)
        self.label_19 = QtGui.QLabel(self.layoutWidget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_10.addWidget(self.label_19)
        self.y_top = QtGui.QLineEdit(self.layoutWidget_3)
        self.y_top.setObjectName(_fromUtf8("y_top"))
        self.horizontalLayout_10.addWidget(self.y_top)
        self.label_20 = QtGui.QLabel(self.layoutWidget_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_10.addWidget(self.label_20)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.Button_Done = QtGui.QPushButton(self.groupBox)
        self.Button_Done.setEnabled(True)
        self.Button_Done.setGeometry(QtCore.QRect(654, 472, 111, 31))
        self.Button_Done.setDefault(True)
        self.Button_Done.setFlat(False)
        self.Button_Done.setObjectName(_fromUtf8("Button_Done"))
        IsoCenter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(IsoCenter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        IsoCenter.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(IsoCenter)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        IsoCenter.setStatusBar(self.statusbar)

        self.retranslateUi(IsoCenter)
        QtCore.QMetaObject.connectSlotsByName(IsoCenter)

    def retranslateUi(self, IsoCenter):
        IsoCenter.setWindowTitle(_translate("IsoCenter", "IsoCenter Definition", None))
        self.groupBox_2.setTitle(_translate("IsoCenter", "IsoCenter", None))
        self.Button_detectIsoCenter.setText(_translate("IsoCenter", "Choose IsoCenter", None))
        self.Button_SetIsoCenter.setText(_translate("IsoCenter", "Lock", None))
        self.label_5.setText(_translate("IsoCenter", "x_Spot=", None))
        self.label_6.setText(_translate("IsoCenter", "y_Spot=", None))
        self.groupBox_3.setTitle(_translate("IsoCenter", "Data", None))
        self.Button_LoadSpot.setText(_translate("IsoCenter", "Load Collimator Image", None))
        self.groupBox_4.setTitle(_translate("IsoCenter", "Field Limits", None))
        self.Button_GetField.setText(_translate("IsoCenter", "Detect Field edges", None))
        self.Button_SetFieldLimits.setText(_translate("IsoCenter", "Lock", None))
        self.label_15.setText(_translate("IsoCenter", "Field Limits: x = [", None))
        self.label_17.setText(_translate("IsoCenter", ";", None))
        self.label_18.setText(_translate("IsoCenter", "]", None))
        self.label_16.setText(_translate("IsoCenter", "                    y = [", None))
        self.label_19.setText(_translate("IsoCenter", ";", None))
        self.label_20.setText(_translate("IsoCenter", "]", None))
        self.Button_Done.setText(_translate("IsoCenter", "Done", None))

from matplotlibwidgetFile import matplotlibWidget
