# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IsoCenter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IsoCenter(object):
    def setupUi(self, IsoCenter):
        IsoCenter.setObjectName("IsoCenter")
        IsoCenter.resize(937, 615)
        self.centralwidget = QtWidgets.QWidget(IsoCenter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Button_LoadSpot = QtWidgets.QPushButton(self.groupBox_3)
        self.Button_LoadSpot.setEnabled(True)
        self.Button_LoadSpot.setDefault(True)
        self.Button_LoadSpot.setFlat(False)
        self.Button_LoadSpot.setObjectName("Button_LoadSpot")
        self.gridLayout_5.addWidget(self.Button_LoadSpot, 0, 0, 1, 1)
        self.Text_Filename = QtWidgets.QTextEdit(self.groupBox_3)
        self.Text_Filename.setEnabled(True)
        self.Text_Filename.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Text_Filename.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Text_Filename.setObjectName("Text_Filename")
        self.gridLayout_5.addWidget(self.Text_Filename, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Button_detectIsoCenter = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_detectIsoCenter.setAutoFillBackground(False)
        self.Button_detectIsoCenter.setCheckable(True)
        self.Button_detectIsoCenter.setChecked(False)
        self.Button_detectIsoCenter.setDefault(True)
        self.Button_detectIsoCenter.setObjectName("Button_detectIsoCenter")
        self.gridLayout_4.addWidget(self.Button_detectIsoCenter, 0, 0, 1, 1)
        self.Button_SetIsoCenter = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_SetIsoCenter.setAutoFillBackground(False)
        self.Button_SetIsoCenter.setDefault(True)
        self.Button_SetIsoCenter.setObjectName("Button_SetIsoCenter")
        self.gridLayout_4.addWidget(self.Button_SetIsoCenter, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.SpotTxt_x = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.SpotTxt_x.setDecimals(1)
        self.SpotTxt_x.setMaximum(10000.0)
        self.SpotTxt_x.setSingleStep(0.1)
        self.SpotTxt_x.setProperty("value", 0.0)
        self.SpotTxt_x.setObjectName("SpotTxt_x")
        self.horizontalLayout_2.addWidget(self.SpotTxt_x)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.SpotTxt_y = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.SpotTxt_y.setDecimals(1)
        self.SpotTxt_y.setMaximum(10000.0)
        self.SpotTxt_y.setSingleStep(0.1)
        self.SpotTxt_y.setObjectName("SpotTxt_y")
        self.horizontalLayout_2.addWidget(self.SpotTxt_y)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.Display_IsoCenter = matplotlibWidget(self.groupBox)
        self.Display_IsoCenter.setMinimumSize(QtCore.QSize(400, 400))
        self.Display_IsoCenter.setObjectName("Display_IsoCenter")
        self.gridLayout_2.addWidget(self.Display_IsoCenter, 0, 0, 6, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.Button_Done = QtWidgets.QPushButton(self.groupBox)
        self.Button_Done.setEnabled(True)
        self.Button_Done.setDefault(True)
        self.Button_Done.setFlat(False)
        self.Button_Done.setObjectName("Button_Done")
        self.gridLayout_2.addWidget(self.Button_Done, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        IsoCenter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IsoCenter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        IsoCenter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IsoCenter)
        self.statusbar.setObjectName("statusbar")
        IsoCenter.setStatusBar(self.statusbar)

        self.retranslateUi(IsoCenter)
        QtCore.QMetaObject.connectSlotsByName(IsoCenter)

    def retranslateUi(self, IsoCenter):
        _translate = QtCore.QCoreApplication.translate
        IsoCenter.setWindowTitle(_translate("IsoCenter", "IsoCenter Definition"))
        self.groupBox_3.setTitle(_translate("IsoCenter", "Data"))
        self.Button_LoadSpot.setText(_translate("IsoCenter", "Load Collimator Image"))
        self.groupBox_2.setTitle(_translate("IsoCenter", "IsoCenter"))
        self.Button_detectIsoCenter.setText(_translate("IsoCenter", "Detect (Draw ROI)"))
        self.Button_SetIsoCenter.setText(_translate("IsoCenter", "Lock"))
        self.label_5.setText(_translate("IsoCenter", "x_Spot="))
        self.label_6.setText(_translate("IsoCenter", "y_Spot="))
        self.Button_Done.setText(_translate("IsoCenter", "Done"))

from RadiAIDD.Backend.UI._matplotlibwidgetFile import matplotlibWidget
