# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# adapted from https://raw.githubusercontent.com/clEsperanto/pyclesperanto_prototype/master/.github/workflows/test_and_deploy.yml
# see /license_thirdpary/license_pyclesperanto_prototype
name: test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.platform }} ( ${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest] #, macos-latest]  # windows-latest broken for now
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up conda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install pocl
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: conda install -y pocl
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python --version
          conda install -y pyopencl
          python -m pip install --upgrade pip
          pip install setuptools wheel pytest pytest-cov pytest-benchmark dask
          pip install -e .
      - name: Test
        shell: bash -l {0}
        run: pytest -v --cov=./ --cov-report=xml
      - name: Coverage
        uses: codecov/codecov-action@v1
